### PR TITLE
Handle outdated advanced search urls

### PR DESCRIPTION
**Pull request by mddilley**
## Associated issues
Closes https://github.com/cityofaustin/atd-data-tech/issues/19687

## Testing
**URL to test:** 

https://deploy-preview-1480--atd-moped-main.netlify.app/moped/projects?filters=%5B%7B%22field%22%3A%22current_phases%22%2C%22operator%22%3A%22string_equals_case_insensitive%22%2C%22value%22%3A%22Planned%22%7D%5D&isOr=false

**Steps to test:**
1. Go to [this link](https://deploy-preview-1480--atd-moped-main.netlify.app/moped/projects?filters=%5B%7B%22field%22%3A%22current_phases%22%2C%22operator%22%3A%22string_equals_case_insensitive%22%2C%22value%22%3A%22Planned%22%7D%5D&isOr=false) that contains a non-existent field name in the filter search params part of the url
2. Read the error message displayed in the app and check if it makes sense to you
3. Click the "click here" link to navigate to the DTS service request form. Make sure the error message is populated inside the **Describe the problem** input in the form

---
#### Ship list
- [x] Code reviewed 
- [x] Product manager approved
- [x] Product manager checked [DB view dependencies](https://atd-dts.gitbook.io/moped-documentation/product-management/updating-the-arcgis-online-components-database-view)
- [x] Product manager added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#) if applicable
   - Added `Manually edit your copied URL in your browser with a invalid field name and see that an error message appears identifying the invalid field`

### CODE REVIEW

**Review by johnclary — APPROVED** [review]
Mike, I think this is a great approach to handling these errors. I have some thoughts about future enhancements, and I think what you have is great to go 🚢 

* It will be ugly, but it might be good to include the entire requested URL in the error message
* It might be nice to offer the user a working query string with the problematic piece removed
* ☝️ on that note, it might be nice to make a customized fallback component instead of the generic **Something went wrong**, since we know specifically what went wrong. that might be a fun enhancement down the road


🚢 🚢 🚢 🚢

**Review by chiaberry — APPROVED** [review]
🚢 ! This will be so helpful to keep track of this type of error. Well as long as someone submits the ticket. What about in the future adding an Activity Metrics event......

I agree with John that a fun future enhancement could be a custom fallback component, especially since the feedback to "try refreshing the page" is not going to address this specific error.

**Comment by mddilley** [comment]
@johnclary @chiaberry Thank y'all for these suggestions! I collected them in https://github.com/cityofaustin/atd-data-tech/issues/20006 so we can check back in after monitoring how well the saved views feature is adopted. 🔍

**Review by tillyw — APPROVED** [review]
this looks great and +1 to but John and Chia's comments! i think including the url in the request could be very helpful, and providing the user with a url sans the broken field might make it pretty easy for them to recreate the url with an updated version of the query

**Pull request merged**
