### PR TITLE
Reduce messages and errors on JS console & handful of spelling fixes

### PR DESCRIPTION
**Pull request by frankhereford**
There are still more errors & messages to run down, but this PR focuses on the default project page (ProjectSummary.js, ProjectSummaryMap.js) and the authentication system (user.js). These pages should load without errors and unrelated messages,  and you should be able to use the logging level controls to get the types of feedback you want. There are some interactions with the components on the project summary page that still generate errors (work ongoing), but the page loads quietly now before user interaction.

I hope to get some more of these quieted in the near future, but I'm going to submit this PR as is to avoid having multiple unrelated changes in one pull request. 

## Associated issues

_none_

## Testing
**URL to test:** https://flh-console-errors--atd-moped-main.netlify.app/moped

**Steps to test:**

- [ ] Authentication working and observe that you can turn on messages from it [here](https://github.com/cityofaustin/atd-moped/blob/flh_console_errors/moped-editor/src/auth/user.js#L152-L154). 
- [ ] Visit a project summary page
- [ ] Evaluate changes to `ProjectSummary.js` and `ProjectSummaryMap.js` in particular

---

#### Ship list
- [ ] Code reviewed 
- [ ] ~Product manager approved~ n/a
- [ ] Added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#gid=776973707)

### CODE REVIEW

**Review by sergiogcx — CHANGES_REQUESTED** [review]
@amenity @patrickm02L @mateoclarke 

Another surprise PR, no issue for this work. While I appreciate the cleanup, this introduces a regression to the `ProjectSummaryMapFallback` component by removing `stopReportingRuntimeErrors` which is intended to remove the annoying error overlay in the local environment.

**Comment by chiaberry** [comment]
@sergiogcx are you still getting the overlay when running locally? I am not seeing it. It would show up on projects with no features, right?

**Comment by chiaberry** [comment]
Usually I see these console errors when viewing projects w/o map components, and they are gone with these changes.
Screen Shot 2021-11-22 at 12 48 28 PM

**Comment by sergiogcx** [comment]
> @sergiogcx are you still getting the overlay when running locally? I am not seeing it. It would show up on projects with no features, right?

@chiaberry I think this clean up is necessary, don't get me wrong. All I know is that ProjectSummaryMapFallback is also used in other parts of the page and this PR potentially affects it.

In short, my main protestation is the refactor of potentially important code without an issue. Is that fair?

**Comment by amenity** [comment]
I don't have anything to weigh in on here!

**Comment by johnclary** [comment]
I have mentioned in dev sync that there's a standing bounty (not sure what the reward is yet) for crushing console errors.

I have no problem with a PR being opened as a starting point for a discussion, and I encourage y'all to raise your concerns here so as long as it's constructive.

@sergiogcx since you have concerns about a portion of this PR, I suggest @frankhereford separate the map fallback refactoring into a separate `Tech Debt` issue we can dedicate time to discussing it without breaking sprint. 

The remaining changes look minor so let's get them reviewed and merged.

**Comment by sergiogcx** [comment]
@johnclary I look forward to that conversation, I keep stumbling into these mystery PRs. Some clarification about the agile process and how these bounties will help.

**Pull request closed without merging**
