### PR TITLE
Fixes bug where "Current phase" displays as blank in the Project List View

### PR DESCRIPTION
**Pull request by tillyw**
Fixes https://github.com/cityofaustin/atd-data-tech/issues/6344

- Fixes bug where "Current phase" displays as blank in the Project List View
- All projects with a "Current phase" have that phase displayed in the Project List View, those without a current phase display a "-"
- Creates new join in Project List View to display the name of the phase in the moped_proj_phases table that is set to current phase, if one exists (only one project can be set to current phase at a time)

This PR includes database changes and will require creating a test instance to QA.

Screen Shot 2021-06-10 at 4 26 37 PM

### CODE REVIEW

**Review by amenity — APPROVED** [review]
Beautiful! Thanks for the snappy work, @tillyw & @chiaberry !!

**Comment by sergiogcx** [comment]
@tillyw @johnclary sorry I had been looking yesterday, and I had been reviewing but for some reason I kept getting pulled by a meeting or something else.

I got stuck in the middle of the review because I was wondering if this PR would affect the filter work @chiaberry was working on.

Retaking the review process now,

**Comment by chiaberry** [comment]
It won't affect my filter work. Let me know what questions come up, Tilly
and I paired on it so i can answer/explain what we did.

**Comment by sergiogcx** [comment]
@chiaberry right, it looks like the filters work, but whenever we filter by current phase, we are actually filtering by the moped_project column and not by the value provided by the new column Tilly created.

**Review by sergiogcx — APPROVED** [review]
It works! 🙌  🥳  Thanks @tillyw for taking care of this :)

**Review by mateoclarke — COMMENTED** [review]
👍

**Comment by tillyw** [comment]
🙌

**Pull request merged**
