### PR TITLE
Search Signal Projects from Signal Dashboard View

### PR DESCRIPTION
**Pull request by chiaberry**
## Associated issues

https://github.com/cityofaustin/atd-data-tech/issues/7966

## Testing
**URL to test:** 
https://7966-search-signal-projects--atd-moped-main.netlify.app/moped/dashboard

**Steps to test:**
Material table has a search option in the upper right hand corner of table. Use it to see what you can find in the table. 

---
#### Ship list
- [x] Code reviewed 
- [x] Product manager approved
- [x] Added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#gid=776973707)

### CODE REVIEW

**Review by frankhereford — APPROVED** [review]
Looks great to me - 🚢 ! I found that I was able to search and find matches based on the following columns in the table:

* Project Name
* Project Sponsor
* Project Partners

**Comment by amenity** [comment]
This looks great, @chiaberry! 

I **was able to search** by values in these columns
- Project name
- Current phase
- Contractor/contract
- Status update
- Funding source
- Project DO #
- Designer
- Inspector
- Construction start (the month or the year, but not a precise date)
- Project completion (the month or the year, but not a precise date)

I **can't search** by two columns @frankhereford was able to use:
- Project sponsor 
- Project partners (I don't see this field on the table)
nor 
- Signal ID
- Project type 

Any idea why Frank and I are seeing different behavior? 

Should I create backlog issues for exposing "Project sponsor" and "Project type" in search?

**Review by sergiogcx — APPROVED** [review]

**Comment by frankhereford** [comment]
> Any idea why Frank and I are seeing different behavior?
> 
> Should I create backlog issues for exposing "Project sponsor" and "Project type" in search?

This is entirely on me - I was looking at the projects listing page. On further testing, I am getting the same results you are. Unable to search on the following: 

* Signal ID
* Project Types
* Project Sponsor
* Project Partners

Sorry about causing that confusion - thanks!

**Comment by amenity** [comment]
@chiaberry - should I create backlog issues to include "Project type" and "Project sponsor" in search, or is that a configuration setting we can add to this PR?

**Comment by chiaberry** [comment]
Best bet would be to make a backlog issue. It's not a straightforward thing to turn on, I don't know why its not searching that as is.

**Review by amenity — APPROVED** [review]
LSTM! 🙏✨

**Comment by amenity** [comment]
New issue for additional filtering functionality: https://github.com/cityofaustin/atd-data-tech/issues/8098

**Pull request merged**
