### PR TITLE
Always show dev environment alert banner except in production

### PR DESCRIPTION
**Pull request by johnclary**
## Associated issues
https://github.com/cityofaustin/atd-data-tech/issues/10786

## Testing

Test locally and [deploy preview](https://deploy-preview-878--atd-moped-main.netlify.app/).

**Steps to test:**
Verify the alert banner displays.

Screen Shot 2022-11-15 at 8 46 51 PM

---
#### Ship list
- [x] Code reviewed 
- [x] Product manager approved
- [ ] Added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#) if applicable

### CODE REVIEW

**Review by frankhereford — APPROVED** [review]
🚀 Spun it up locally, I think it's 🎯💯. 

Temp-250x250


Make it red ... you know you want to ... this is not the production environment you're looking for... (joking!)

**Review by mddilley — APPROVED** [review]
Nice! Super helpful for us to quickly see which one is the real deal 🙌

**Comment by johnclary** [comment]
do folks have a strong opinion about using the red `error` banner instead? i don't think @frankhereford was fully joking ;)

Screen Shot 2022-11-16 at 12 43 20 PM

**Review by chiaberry — APPROVED** [review]
no strong opinions on color! just glad this is happening and will be on our test apps too

**Review by tillyw — APPROVED** [review]
thank you for doing this! i don't have any strong feelings on the color. i think i was the one who implemented this originally and i don't remember why we didn't go with red but i remember that was the consensus at the time. open to changing it if people prefer!

**Comment by johnclary** [comment]
in the spirit of not arbitrarily undoing past decisions we'll keep it blue. thanks y'all!

**Pull request merged**
