### PR TITLE
Implement "Project website" field #7069

### PR DESCRIPTION
**Pull request by sergiogcx**
Closes https://github.com/cityofaustin/atd-data-tech/issues/7069

** Database and UI changes = moped-test please

### CODE REVIEW

**Review by frankhereford — APPROVED** [review]
Saves input and opens in a new tab - looks awesome!

**Review by amenity — APPROVED** [review]
LSTM! 🚢 ✨

✅  Added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#gid=776973707)

**Comment by patrickm02L** [comment]
Nice. Approved!

**Review by mateoclarke — COMMENTED** [review]
👍

**Pull request merged**
