### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by amenity**
## Review
Current: https://github.com/cityofaustin/atd-moped 
Proposed: https://github.com/cityofaustin/atd-moped/tree/amenity-readme-update

- `MPD` and `Mobility Project Database` --> `Moped`
- Update ATD and PWD references to TPW
- General cleanup to reduce redundancy w/ DTS website
- Refine alt-text

---
#### Ship list
- [x] Code reviewed 
- [x] Product manager approved
- [ ] ~Added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#) if applicable~

### CODE REVIEW

**Review by frankhereford — APPROVED** [review]
Looks great - thank you @amenity. 🚢 🚀 📚 


image

**Review by chiaberry — APPROVED** [review]
this is much better than what I wrote up! I will remove my updates to the main readme from my PR

**Review by mddilley — APPROVED** [review]
Looks great! Love that this points to the DTS site and other resources now 🙌 ✨

**Comment by amenity** [comment]
Thanks, y'all!

**Pull request merged**
