### PR TITLE
Implement design and layout refinements to "Summary" tab #7491

### PR DESCRIPTION
**Pull request by sergiogcx**
Closes https://github.com/cityofaustin/atd-data-tech/issues/7491

- Removes text under map
- Moves map controls to bottom right
- Pencil icon is now outline
- Updates menu options (and dialog)
- Updates text color to #828282 (secondary text)
- website is 1/2 the width (xs=6)

#### Live Demo
https://deploy-preview-461--atd-moped-main.netlify.app/moped/session/signin

### CODE REVIEW

**Review by mateoclarke — APPROVED** [review]
🚢 💨 ✨

**Comment by patrickm02L** [comment]
Alignment. Scoot the pencil and the plus button to the left so that they're in line with the other pencils.

screencapture-deploy-preview-461-atd-moped-main-netlify-app-moped-projects-351-2021-11-09-07_53_54

**Comment by amenity** [comment]
@patrickm02L - [here's a follow-up issue](https://github.com/cityofaustin/atd-data-tech/issues/7698) for ☝🏻 .

**Comment by sergiogcx** [comment]
@patrickm02L Review please: https://github.com/cityofaustin/atd-moped/pull/462

**Pull request merged**
