### PR TITLE
Clean up project team table #8178

### PR DESCRIPTION
**Pull request by sergiogcx**
## Associated issues

This PR gets rid of that nasty setTimeout pattern once and for all.

Close https://github.com/cityofaustin/atd-data-tech/issues/8178

## Testing

https://deploy-preview-526--atd-moped-main.netlify.app/moped/projects/345?tab=team

**Steps to test:**

https://user-images.githubusercontent.com/5282430/149504378-b8c12784-18d6-4c77-8690-9edaa5cc80c8.mp4

---
#### Ship list
- [ ] Code reviewed 
- [ ] Product manager approved
- [ ] Added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#gid=776973707)

### CODE REVIEW

**Review by frankhereford — APPROVED** [review]
🧹  ⏲️   ➡️  🏆 

Getting that timeout callback is awesome - thank you for observing that and crushing it!

**Review by amenity — CHANGES_REQUESTED** [review]
"Notes" column should not display "Null" when empty.
Screen Shot 2022-01-14 at 10 41 08 AM

**Comment by sergiogcx** [comment]
@amenity thanks, can you check again?

**Comment by johnclary** [comment]
> 🧹 ⏲️ ➡️ 🏆
> 
> Getting that timeout callback is awesome - thank you for observing that and crushing it!

+1 @sergiogcx way to take us to the red on this one!

Screen Shot 2022-01-14 at 5 46 43 PM

**Pull request merged**
