### PR TITLE
Use wider team role select menu

### PR DESCRIPTION
**Pull request by johnclary**
## Associated issues
- https://github.com/cityofaustin/atd-data-tech/issues/10609

## Testing
**URL to test:**  [Deploy preview](https://moped.austinmobility.io/moped/projects/1720?tab=team)

**Steps to test:**
1. Navigate to the Team tab of any project.
2. Add a team member
3. Edit the team member roles and observe:
- the drop-down menu is 50% of the screen width and is horizontally centered under the "Role" column
- when unfocused, the input menu has linebreaks between the selected role options

---
#### Ship list
- [ ] Code reviewed 
- [ ] Product manager approved
- [ ] Added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#) if applicable

### CODE REVIEW

**Comment by johnclary** [comment]
Before:
Screen Shot 2022-10-25 at 2 37 24 PM
Screen Shot 2022-10-25 at 2 37 19 PM

After:
Screen Shot 2022-10-25 at 2 39 32 PM
Screen Shot 2022-10-25 at 2 39 26 PM

**Comment by patrickm02L** [comment]
Small improvements. (red outline for emphasis only, render without)
- left align the Role drop down menu
- bring right edge in so that it lives within the project teams thin grey outlined frame.

before

**Comment by johnclary** [comment]
thanks @patrickm02L. consider this a compromise?

Screen Shot 2022-10-26 at 12 07 19 PM

it does look possible to manually set the popup offset to try to align it with the "Role" header, but will be tricky. Finding the right edge of the table is also tricky, because this Menu is absolute positioned outside of normal flow.

**Review by patrickm02L — APPROVED** [review]
This is so nice! Thanks for the compromise. It looks good in the middle where you placed it. 🤘

https://user-images.githubusercontent.com/5566727/198081896-10a9be87-e35c-4f21-8552-76f74d7bcaf6.mp4

**Review by chiaberry — APPROVED** [review]
i think personally I prefer the horizontal origin for the anchor and transform to be left, but i dont feel super strongly about it one way or another.

**Comment by johnclary** [comment]
OK—thank you both! I'm going to leave it has horiz centered b/c left-aligned things get a little wacky on larger displays.

**Pull request merged**
