### PR TITLE
Fixes typo in sidewalk ramps component_subtype

### PR DESCRIPTION
**Pull request by johnclary**
## Associated issues
Resolves https://github.com/cityofaustin/atd-data-tech/issues/9313 🐏 

## Testing
**URL to test:** 
- locally or Moped Test

**Steps to test:**
1. Navigate to a project's **Map** tab
2. Click the **Add new component** button
3. Select **Sidewalk** as the component **Type**
4. Select **Ramps** as the component **Subtype**
5. Select a location on the map and save the component
6. Verify that the component subtype is spelled "Ramps", not "Rams"

---
#### Ship list
- [x] Code reviewed 
- [ ] Product manager approved
- [ ] Added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#) if applicable

Screen Shot 2022-05-27 at 9 11 11 AM

### CODE REVIEW

**Review by chiaberry — APPROVED** [review]
original

**Review by mateoclarke — APPROVED** [review]
🐏 🐏 🐏

**Comment by chiaberry** [comment]
For the record, the image I posted above is of ramps

**Review by frankhereford — APPROVED** [review]
# 🚫 🐏 

Thanks John!

**Review by mddilley — APPROVED** [review]
Test steps work just as expected 👍  and TIL about [ramps (the vegetable)](https://www.eater.com/2015/4/10/8384255/ramps-season-explained) thanks to @chiaberry

**Comment by johnclary** [comment]
going to go ahead and merge this to clear it from @amenity's todo list.

**Pull request merged**
