### PR TITLE
Add `marginRight` and flex`<Box/>` to prevent text/button overlap

### PR DESCRIPTION
**Pull request by mateoclarke**
## Associated issues

Fixes https://github.com/cityofaustin/atd-data-tech/issues/17689

### Before

Screenshot 2024-06-05 at 5 48 43 PM

### After

Screenshot 2024-10-14 at 4 13 34 PM

## Testing
**URL to test:** 
[https://deploy-preview-1455--atd-moped-main.netlify.app/moped/projects/2037?tab=map](https://deploy-preview-1455--atd-moped-main.netlify.app/moped/projects/2037?tab=map)

**Steps to test:**
1. Look at the existing components and confirm the Component name text does not overlap with the Zoom In Icon. 
2. Create a new component with a long name (ex: a traffic signal like 25: MLK & Congress).

---
#### Ship list
- [ ] Code reviewed 
- [ ] Product manager approved
- [ ] Product manager checked [DB view dependencies](https://atd-dts.gitbook.io/moped-documentation/product-management/updating-the-arcgis-online-components-database-view)
- [ ] Product manager added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#) if applicable

### CODE REVIEW

**Review by johnclary — APPROVED** [review]
I can make my location descriptions as long as I please! Very nice to see flex box come to the rescue 🚢 🚢 🚢 🚢 🚢

**Review by chiaberry — APPROVED** [review]
Screenshot 2024-10-16 at 1 41 46 PM

Thank you for addressing this! such an unsightly bug ✅

**Review by tillyw — APPROVED** [review]
so much better ✨ tested and confirmed with a signal component with a long name. thanks for fixing this!

**Review by mddilley — APPROVED** [review]
Awesome!!! I tested with the longest component name there is and also a really long location description. Neither overlapped with the icon. 🙌 🚢

**Review by roseeichelmann — APPROVED** [review]
i had just stumbled upon this bug the other day, sooo nice to have this fixed!! :sparkles:

**Pull request merged**
