### PR TITLE
Add filtering capability to signal dashboard table

### PR DESCRIPTION
**Pull request by chiaberry**
## Associated issues

https://github.com/cityofaustin/atd-data-tech/issues/8098

## Testing
**URL to test:** 
 https://8098-column-filter--atd-moped-main.netlify.app/moped/dashboard 

**Steps to test:**

Test the filters that appear at the top of the signals table. Specifically test that 
 - project types
 - task orders
 - project sponsors
are able to be filtered. Also we have the option to change the filter icon, if that is desired. 

---
#### Ship list
- [x] Code reviewed 
- [x] Product manager approved
- [x] Added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#gid=776973707)

### CODE REVIEW

**Review by frankhereford — APPROVED** [review]
This works great. This is a really elegant solution entirely in the front-end app too.

**Review by amenity — APPROVED** [review]
Niiiiice, @chiaberry! This works so perfectly... Big points for Material Table. 😎 👏

**Comment by amenity** [comment]
Any idea why we can't filter on signals IDs, @chiaberry ?

**Comment by chiaberry** [comment]
@amenity same reason why the other columns weren't filtering -- the data we have for those entries are more complex than just what is being shown, so material table doesn't know how to filter it. 

do you want me to make signal ids also filterable?

**Comment by amenity** [comment]
I'm down with Patrick's idea to use a dark grey instead for the filters.

**Review by mateoclarke — APPROVED** [review]
👏 👏 👏  
Really well done Chia!

🚢 💨 ✨

**Pull request merged**
