### PR TITLE
Add two new entities

### PR DESCRIPTION
**Pull request by chiaberry**
## Associated issues

https://github.com/cityofaustin/atd-data-tech/issues/16673

## Testing
run locally

**Steps to test:**

You can see the two new entities in the Project Lead or Project Sponsor selections on the summary page. 

---
#### Ship list
- [ ] Code reviewed 
- [x] Product manager approved
- [ ] ~Added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#) if applicable~

### CODE REVIEW

**Comment by chiaberry** [comment]
@amenity Do you know what workgroups these two new entities should be associated with? Here is what some of the entities are matched up with

Screenshot 2024-04-10 at 8 07 46 PM

**Comment by chiaberry** [comment]
@amenity the screenshot doesnt have the whole list of entities, we have 42 entities and my screenshot couldnt get them all in. project delivery and smo are in there

**Review by mddilley — APPROVED** [review]
Tested locally, and I see the new entities! 🚢  🙌 🚢

**Review by amenity — APPROVED** [review]
🚶🏻 🚴🏻‍♂️ ✔️  

Thanks for seeing this one along @chiaberry!

**Pull request merged**
