### PR TITLE
implements small refinements to timeline tab

### PR DESCRIPTION
**Pull request by tillyw**
## Associated issues
fixes https://github.com/cityofaustin/atd-data-tech/issues/6352

## Testing
**URL to test:** 
https://deploy-preview-589--atd-moped-main.netlify.app/moped/projects

**Steps to test:**
go to timeline tab, add a project phase with a description. edit an exiting project phase description.

---
#### Ship list
- [ ] Code reviewed 
- [ ] Product manager approved
- [ ] Added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#gid=776973707)

### CODE REVIEW

**Review by amenity — CHANGES_REQUESTED** [review]
@tillyw - this looks great, thanks! However I'm second-guessing removing "Completion estimate" and renaming "Date completed". 🤦‍♀️  Can we put those back?

**Comment by tillyw** [comment]
> @tillyw - this looks great, thanks! However I'm second-guessing removing "Completion estimate" and renaming "Date completed". 🤦‍♀️ Can we put those back?

@amenity yes no problem i've reverted those changes! @mateoclarke @chiaberry this is ready for review

**Comment by amenity** [comment]
@tillyw Super, thanks! One last thing: Can you widen the "Description" column, please? The "complete" column can be narrowed.

**Review by chiaberry — APPROVED** [review]

**Review by mateoclarke — COMMENTED** [review]
👍

**Pull request merged**
