### PR TITLE
Promote release v0.1.0 to production

### PR DESCRIPTION
**Pull request by mateoclarke**
[v0.1.0 Release Notes](https://github.com/cityofaustin/atd-moped/releases/tag/v0.1.0)

Features in this release should be reviewable in the current staging instance of Moped (aka: `main` branch). 
https://moped.austinmobility.io/moped

### CODE REVIEW

**Comment by amenity** [comment]
@sergiogcx @mateoclarke Should the Activity feed be capturing edits to Project phases? Or is there another way I can test it?

**Comment by sergiogcx** [comment]
@amenity looking into this, it seems the events are getting sent to AWS correctly, will check the rest of the pipeline:

**Comment by sergiogcx** [comment]
Messages are getting queued, another good sign. Continuing troubleshooting:

**Comment by sergiogcx** [comment]
Ah, there is a problem in the SQS code, it appears the messages are failing validation. I put the validation there as a security measure, and given a couple new values we added (database_id, and workgroup_id) the validation raises those issues as unknown fields:

**Pull request merged**
