### PR TITLE
Move map from Map tab to Project list view

### PR DESCRIPTION
**Pull request by mddilley**
## Associated issues
https://github.com/cityofaustin/atd-data-tech/issues/16966

This one moves the projects map from a tab in the main app view to the project list view where it is toggled on/off with a switch. I'd appreciate any feedback on design, etc. 🙏 No rush since the [next issue](https://github.com/cityofaustin/atd-data-tech/issues/9927) isn't blocked by this.

## Testing
**URL to test:** 

Local

**Steps to test:**
1. Go to the Projects table
2. See that there is a switch next to the **Download** export button that toggles the map view
3. See that the map that was in a tab in the [last PR](https://github.com/cityofaustin/atd-moped/pull/1276) now replaces the list when the switch is on
4. I also made changes to the responsive behavior of the row with the search bar, download button, and switch so feedback on that would be great, thanks!

---
#### Ship list
- [x] Code reviewed 
- [x] Product manager approved
- [ ] ~Added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#) if applicable~

### CODE REVIEW

**Review by amenity — CHANGES_REQUESTED** [review]
The map looks beautiful! 😊 🗺️ ✨ 

Responsive-wise, I like the switch and download button bumping down to a new line. It looks like there's still an the buttons are no longer full-width at the smallest breakpoint.

Screenshot 2024-05-07 at 12 07 41 PM

**Comment by mddilley** [comment]
@amenity Thanks for catching that! I fixed that so that all breakpoints are covered now. 🙏

**Review by amenity — APPROVED** [review]
👌🏻 Looks great, thanks!

**Review by johnclary — COMMENTED** [review]
this looks awesome! so exciting this come to life 🚀 

on the small display size, i wonder if we could get the search button, download icon, and map toggle in one row. at that breakpoint you could hide the download button label and only show the icon.

one other observation is that i think the map toggle might be better placed to the left of the search button. i think folks are going to be clicking that much more often than the download button. 

just food for thought! 🙌 🚢 🚢 🚢 🚢 🚢

**Review by chiaberry — APPROVED** [review]
Looks good!

**Comment by chiaberry** [comment]
also now that i am looking at the next PR, I like the toggle saying "Map" versus show map.

**Pull request merged**
