### PR TITLE
Update moped scooter svg

### PR DESCRIPTION
**Pull request by jgabitto**
- Closes https://github.com/cityofaustin/atd-data-tech/issues/6723
- Replace moped.svg file with new moped.svg file

### CODE REVIEW

**Review by sergiogcx — APPROVED** [review]
Nice! Thank you! 🛵

**Comment by mateoclarke** [comment]
@amenity, whats the change in color here? It seems like the new and the old one are both Tomato Red `#fe6748`. Am I missing something?

**Review by mateoclarke — COMMENTED** [review]
It's not clear to me how this SVG file looks different. Am I missing something? Either way, I think its worth running the markup through a minified for a marginal performance improvement. 

I've used the [SVGO](https://github.com/svg/svgo) library before for command line bulk minification, but this web UI for it works for one-offs like this one: https://jakearchibald.github.io/svgomg/

**Comment by amenity** [comment]
@mateoclarke - the new one is supposed to be #ff6549... it's pretty close to the other one. 

Screen Shot 2021-08-02 at 11 25 55 PM

Screen Shot 2021-08-02 at 11 23 55 PM

Good call on minifying, I didn't see all this gross inkscape metadata. This tool works really well, too!

**Comment by jgabitto** [comment]
@mateoclarke @amenity I minified the moped.svg file with the resource Mateo suggested and replaced the other one. Let me know what you all think.

**Review by mateoclarke — APPROVED** [review]
With the svg minified and Amenity's confirmation about the logo, I'd say good to ship... 🚢

**Review by amenity — APPROVED** [review]
Perfect!

**Pull request merged**
