### PR TITLE
Ensures correct construction and completion dates are shown in project list view

### PR DESCRIPTION
**Pull request by johnclary**
## Associated issues
- https://github.com/cityofaustin/atd-data-tech/issues/12264

## Testing
**URL to test:** Local

**Steps to test:**
1. Create a new project.
2. Add a "Construction" phase to the project with a start date populated.
3. Add another "Construction phase to the project with a start populated that is **later** than the previous phase you added.
4. Add a "Completed" phase to the project with the end date populated.
5. Add another Completed phase to the project with no end date populated.
6. From the project list view, confirm that your project's "Construction start" and "Completion date" columns are populated with the dates you entered in step 2 and step 4, respectively. 
---
#### Ship list
- [ ] Code reviewed 
- [ ] Product manager approved
- [ ] Added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#) if applicable

### CODE REVIEW

**Comment by johnclary** [comment]
👋 not urgent / this does not need to ship with today's release.

**Review by mddilley — APPROVED** [review]
Tested locally, and I see accurate construction start and project complete dates in the project list view. Thanks for patching up this unexpected behavior and updating the comments! 🙏 🚢  🚀

**Review by roseeichelmann — APPROVED** [review]
dates look good, works as expected!

**Review by frankhereford — APPROVED** [review]
Thanks for the helpful comments in the file tracking the current state of the view John - super helpful. 🚀

**Review by frankhereford — APPROVED** [review]
Thanks for the helpful comments in the file tracking the current state of the view John - super helpful. 🚀

Huh, not sure how this happened. This PR was just so good, I had to approve it twice.

**Pull request merged**
