### PR TITLE
Reduce table cell sizes for Grid Table

### PR DESCRIPTION
**Pull request by chiaberry**
Changes spacing in Grid Table. 

Changes affect project list view
https://6061-project-table-design--atd-moped-main.netlify.app/moped

and Personnel list view
https://6061-project-table-design--atd-moped-main.netlify.app/moped/staff

### CODE REVIEW

**Review by sergiogcx — APPROVED** [review]
Looks great! 💅  🚢   🚀

**Review by tillyw — APPROVED** [review]
Looks great!!

**Review by mateoclarke — APPROVED** [review]
🚢  👏 🤏

**Review by amenity — APPROVED** [review]
So tite!! LSTM ✨

**Pull request merged**
