### PR TITLE
Tweak add new project workflow

### PR DESCRIPTION
**Pull request by chiaberry**
https://6199-tweak-define-project--atd-moped-main.netlify.app/moped/projects/new

 - [ ] "Name" ---> "Project name"
 - [ ] Remove "Current phase"

@amenity, Does the layout or padding next to change at all after removing current phase?

### CODE REVIEW

**Review by sergiogcx — APPROVED** [review]
Greatness! 🚢

**Review by tillyw — APPROVED** [review]
Looks great!

ZGCOsXy

**Review by amenity — APPROVED** [review]
I think this looks swell, @chiaberry . Thanks

**Review by mateoclarke — APPROVED** [review]
🚢

**Pull request merged**
