### PR TITLE
Sets time zone to UTC when formatting for display

### PR DESCRIPTION
**Pull request by tillyw**
Fixes https://github.com/cityofaustin/atd-data-tech/issues/5682

Formatting display date using UTC fixes issue where incorrect date was rendered. Correct date is now rendered. @sergiogcx, can you please confirm this does not interfere with [this time zone-related PR you merged](https://github.com/cityofaustin/atd-moped/pull/254)?

https://user-images.githubusercontent.com/35410637/113343907-09441900-92f6-11eb-854f-7c66140c4170.mov

### CODE REVIEW

**Review by sergiogcx — CHANGES_REQUESTED** [review]
The old code looks correct: `formattedValue = new Date(formattedValue).toLocaleDateString();`

The problem is not the UI, the problem is that the `date` column is not of type `timestamptz` so it assumes it is already in UTC. 

[The PR you are referring to](https://github.com/cityofaustin/atd-moped/pull/254) fixes this problem by changing the type from timestamp to timestamptz. In short, to fix we just have to transform the date column from type date to timestamptz.

**Review by amenity — APPROVED** [review]
Looks splendid to me!

**Review by mateoclarke — COMMENTED** [review]
So this code change makes sense solving the problem from a UI perspective which was the way the issue was written. But it sounds like @sergiogcx is suggested a database type change which also make sense to me as a better solution closer to the data source and more comprehensive across the UI. 

My question would be, would this change just be to "start date" or do we need to make more changes to date types across the Project table?

**Comment by sergiogcx** [comment]
@tillyw @mateoclarke what would happen if instead of

```
formattedValue = new Date(formattedValue).toLocaleDateString();
```

we use

```
formattedValue = formattedValue;
```

That would make use of the date data RAW without having to change the code.

**Review by mateoclarke — APPROVED** [review]
🚀

**Comment by tillyw** [comment]
Reverted this back to just the UI changes, @sergiogcx can you approve so I can merge? Will circle back around with y'all tomorrow about creating a new issue for the proposed DB changes @mateoclarke

**Review by sergiogcx — APPROVED** [review]

**Comment by sergiogcx** [comment]
Thank you @tillyw

**Pull request merged**
