### PR TITLE
[Bug] Prevent map from zooming in too close #6821

### PR DESCRIPTION
**Pull request by sergiogcx**
Updates MaxZoom across all instances of `<ReactMapGL/>`

### Live Demo:
https://deploy-preview-397--atd-moped-main.netlify.app/

### CODE REVIEW

**Comment by johnclary** [comment]
thanks @sergiogcx! after testing it out I went ahead and bumped it up to maxZoom `20`. 🚢

**Review by johnclary — APPROVED** [review]

**Comment by sergiogcx** [comment]
Thanks @johnclary ! Will merge to main shortly too

**Comment by johnclary** [comment]
@amenity here's Riverside/Coriander at the new max zoom:
Screen Shot 2021-08-16 at 6 43 28 PM

and here it is with imagery:
Screen Shot 2021-08-16 at 6 48 26 PM



and for reference this is the default zoom (16) as of Moped v0.8:
Screen Shot 2021-08-16 at 6 43 36 PM

**Review by mateoclarke — COMMENTED** [review]
👍

**Pull request merged**
