### PR TITLE
display only active users by default

### PR DESCRIPTION
**Pull request by tillyw**
## Associated issues
fixes https://github.com/cityofaustin/atd-data-tech/issues/16519

sets an initial filter state to show only active users on the staff list view. users can choose to remove this filter to see all users.

## Testing
**URL to test:** 

https://deploy-preview-1352--atd-moped-main.netlify.app/

**Steps to test:**

- go to the staff list view
- see that only active users are listed and that this initial filter is already applied
- remove the filter and see that the table displays all users
- refresh the page and see that the initial filter has been reapplied

---
#### Ship list
- [x] Code reviewed 
- [x] Product manager approved
- [ ] Added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#) if applicable

### CODE REVIEW

**Review by roseeichelmann — APPROVED** [review]
this works great!

**Review by mddilley — APPROVED** [review]
Looks great and works great! Thanks for updating! 🙌 🚢

**Review by johnclary — APPROVED** [review]
cool to see how this works! nice!

**Comment by tillyw** [comment]
thanks, y'all!

**Pull request merged**
