### PR TITLE
Make DataGridPro table button dropdowns close after item selection

### PR DESCRIPTION
**Pull request by chiaberry**
## Associated issues

https://github.com/cityofaustin/atd-data-tech/issues/19647

## Testing
**URL to test:** 

https://deploy-preview-1485--atd-moped-main.netlify.app/moped/projects/1973?tab=timeline

**Steps to test:**

Click the Add Phase or Add Milestone button, it shows a menu "add [one record] / From template" 
Click From template. The menu closes when the modal appears. 
Compare to https://moped.austinmobility.io/moped/projects/1822?tab=timeline, where the dropdown menu stays open. 

---
#### Ship list
- [x] Code reviewed 
- [x] Product manager approved
- [x] Product manager checked [DB view dependencies](https://atd-dts.gitbook.io/moped-documentation/product-management/updating-the-arcgis-online-components-database-view)
- ~[ ] Product manager added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#) if applicable~

### CODE REVIEW

**Review by mddilley — CHANGES_REQUESTED** [review]
I confirmed that this works in the project funding, phase, and milestones tables. Love that it plugs right into a shared component of the three tables too. 🙌 I requested a tiny change in naming.

**Review by johnclary — APPROVED** [review]
I see what you did here, and I like it. 🚢 🚢 🚢 🚢 🚢

**Review by mddilley — APPROVED** [review]
Yay for self-closing button menus. Awesome for all these to behave the same! 🚢 😎

**Review by tillyw — APPROVED** [review]
this is a nice enhancement! especially comes in handy if you click away from the modal after selecting 'from template', there is no longer an open menu

**Review by roseeichelmann — APPROVED** [review]
thanks for fixing this! :rocket:

**Pull request merged**
