### PR TITLE
Perform miscellaneous database updates

### PR DESCRIPTION
**Pull request by chiaberry**
## Associated issues

https://github.com/cityofaustin/atd-data-tech/issues/8058

## Testing
**URL to test:** 

Database changes, so must be local or on moped test. 

**Steps to test:**

To see the changes on the moped entity table: Go to a projects summary page and select the partner dropdown. COA ATD Vision Zero is now an option. (Note, when I tested locally, that option moved to the bottom of the list. I'm not sure if the order in the dropdown matters, but if it does we could order by enitity_id)

To see the moped components change, go the map tab, add a new component and look for a Crosswalk with only 2 s. 

---
#### Ship list
- [x] Code reviewed 
- [ ] Product manager approved
- [ ] Added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#gid=776973707)

### CODE REVIEW

**Review by frankhereford — APPROVED** [review]
ezgif-3-cb685c971f

**Review by amenity — COMMENTED** [review]
@chiaberry - thanks! Please update these dropdowns so the option appears in the right spot:
Screen Shot 2022-01-23 at 8 17 25 PM
/1463708/150711726-f1f633f6-c5b8-45ec-a80a-74cab90e99fd.png)

**Comment by chiaberry** [comment]
@amenity, I updated the code to sort the entities by entity_id

**Comment by amenity** [comment]
@chiaberry - thanks! Does this mean that we'll need to add a `sort` column if we want to insert values down the line?

**Comment by chiaberry** [comment]
oh, like if for example there will the COA Fancy Bond Group and you would want it to appear between Aviation and Corridor? Yeah, we would have to come up with a different way to sort/display them then

**Comment by mateoclarke** [comment]
> oh, like if for example there will the COA Fancy Bond Group and you would want it to appear between Aviation and Corridor? Yeah, we would have to come up with a different way to sort/display them then

We could create a `sort` column if we want to control sort order for these values consistently across the UI.

**Review by mateoclarke — APPROVED** [review]
🚢 💨 ✨ 

crossswalk

**Review by amenity — APPROVED** [review]
Nice, thanks!

**Pull request merged**
