### PR TITLE
Adds council districts to seed data

### PR DESCRIPTION
**Pull request by johnclary**
## Associated issues
- https://github.com/cityofaustin/atd-data-tech/issues/11531

## Testing
**URL to test:** Local

**Steps to test:**
1. Start the hasura cluster
2. Connect to the DB and query the districts. Verify there are 10 districts.

```sql
select * from layer_council_district;
```

---
#### Ship list
- [ ] Code reviewed 
- [ ] Product manager approved
- [ ] Added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#) if applicable

### CODE REVIEW

**Review by chiaberry — APPROVED** [review]
I verify 10 districts!

**Review by mddilley — APPROVED** [review]
Yay! The dupe is gone! 🎉 I tested locally and see all 10 council districts 🚀

**Comment by mddilley** [comment]
Also, TIL that TablePlus will show a preview of geography type fields if you hover over them

Screenshot 2023-02-21 at 4 46 25 PM

**Comment by johnclary** [comment]
thanks y'all!

**Pull request merged**
