### PR TITLE
Fix moped DB documentation build step by special casing the architecture detection on GNU/Linux

### PR DESCRIPTION
**Pull request by frankhereford**
## Associated issues

This PR intends to close https://github.com/cityofaustin/atd-data-tech/issues/8264. 

## Testing

This is a tricky one to test. Two routes come to mind:

- [x] Checkout moped on a linux machine running on an actual, metal x86_64 chip and spin up the database. I have done this and it worked as intended.
- [ ] Test the change by _skipping testing_ and merging the PR into main and see if the change allows to DB documentation build step to complete in our automated dev-ops. 
  - This nonsensical approach is the result of us not really having direct access to the actual linux VMs on which this build step happens, I believe. 

---
#### Ship list
- [ ] Code reviewed 
- [x] ~Product manager approved~

### CODE REVIEW

**Comment by amenity** [comment]
Going to bow out of this review, @frankhereford, since I am not running Moped locally and therefore can't test it myself. But thanks for getting it taken care of!

**Review by chiaberry — APPROVED** [review]
I'm able to run the hasura cluster on my machine. Let's test the actions next.

**Review by mateoclarke — APPROVED** [review]
🚢 💨 ✨

**Comment by frankhereford** [comment]
This worked as we hoped; thanks y'all!

**Pull request merged**
