### PR TITLE
Miscellaneous color adjustments

### PR DESCRIPTION
**Pull request by jgabitto**
- Closes https://github.com/cityofaustin/atd-data-tech/issues/6859
- Updated primary main and primary light colors in theme
- Set background color of Table row with `.MuiTableCell-stickyHeader`
- Set background color and text color to AppBar on project pages
- Set indicator color and text color of active tab on project pages

How to view changes
- Visit netlify preview and log in moped
- Go to projects section and look at the table
- Select a project and look at the tabs
- Select a tab and see the change there
- Go to staff section and look at the table

### CODE REVIEW

**Review by sergiogcx — APPROVED** [review]
I like the style changes! That sticky header looks amazing! :shipit: 🚀

**Comment by amenity** [comment]
@jgabitto, I've tried cache-clearing and alternate browsers in the Netlify preview and [Moped Test](https://moped-test.austinmobility.io/moped/projects). I am not able to see the `#ffffff` table header on the Projects/Staff pages.  
Screen Shot 2021-08-10 at 12 32 31 AM

**Comment by jgabitto** [comment]
@amenity So none of the other changes that I've made are being reflected in the netlify preview. For instance, the changes I made to the tabs on the projects page are not showing up as well. Do you know why this is happening?

image

**Comment by sergiogcx** [comment]
@jgabitto that url you took a screen shot is the staging website, not the preview.
@amenity I can see the netlify work.

**Review by mateoclarke — APPROVED** [review]
Code changes look good to ship 🚢 . 

Was going to make the same comment that Sergio just did, it seems like when you thought you were looking at the deploy preview, you were trying SSO for login and getting redirected to the staging site which will show you the current state of `main` branch instead of the branch related to this PR. We can talk about how and why that works more if needed.

**Review by amenity — APPROVED** [review]
Beautiful! Thanks, @jgabitto !

**Pull request merged**
