### PR TITLE
Adds Signal Engineer to Moped Project roles

### PR DESCRIPTION
**Pull request by tillyw**
## Associated issues

fixes https://github.com/cityofaustin/atd-data-tech/issues/8502

## Testing
**URL to test:** 

**Steps to test:**
- Deploy to test branch
- Go to existing project
- Go to team table
- Add new team member
- Select "Signal engineer" as role

---
#### Ship list
- [ ] Code reviewed 
- [ ] Product manager approved
- [ ] Added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#) if applicable

### CODE REVIEW

**Comment by amenity** [comment]
@tillyw is looking into why this isn't showing up in the dropdown on Test:

https://user-images.githubusercontent.com/1463708/157763960-fc86cc04-8734-488c-ada8-307d21a46c8c.mov

**Review by chiaberry — APPROVED** [review]

**Review by amenity — APPROVED** [review]
Works great! Thanks, @tillyw !

**Comment by amenity** [comment]
Merging per Tilly's request. 🦋

**Comment by mateoclarke** [comment]
👍

**Pull request merged**
