### PR TITLE
[Bug] Map error handler not rendering on projects without locations #6228

### PR DESCRIPTION
**Pull request by sergiogcx**
Closes https://github.com/cityofaustin/atd-data-tech/issues/6228

Forces the component to throw an error if there are no features to render.

** Test with moped-test or local environment, which include projects without features.

### CODE REVIEW

**Review by chiaberry — APPROVED** [review]

**Comment by amenity** [comment]
@sergiogcx - I can't get this to deploy on Test tonight. I did on Friday but couldn't turn up any geometry-less projects. Can you send me a project ID for one?

**Comment by amenity** [comment]
Scratch that, deployed and found [a project](https://moped-test.austinmobility.io/moped/projects/226). But I'm not seeing the map error handler. 🤔

Screen Shot 2021-06-01 at 2 54 59 AM

**Comment by chiaberry** [comment]
@amenity I saw it locally, so went to check out the test instance you linked to. I see the map error but just as before im in infinite reload zone too:

**Review by amenity — APPROVED** [review]
Working for me now!
Screen Shot 2021-06-01 at 2 05 06 PM

**Pull request merged**
