### PR TITLE
Update moped theme and remove backgroundColor override

### PR DESCRIPTION
**Pull request by jgabitto**
- Closes https://github.com/cityofaustin/atd-data-tech/issues/6712
- Update properties in theme object
- Remove backgroundColor property from classes.root

### CODE REVIEW

**Comment by sergiogcx** [comment]
@jgabitto It looks like it's not building because the colors variable is not being used, that needs to be fixed:

**Comment by jgabitto** [comment]
> @jgabitto It looks like it's not building because the colors variable is not being used, that needs to be fixed:
> 
> 

Ok removed the colors import

**Review by sergiogcx — APPROVED** [review]
Looks nice! Thanks for fixing those issues. 🚢 🚀 📦

**Comment by amenity** [comment]
Looks great! Thanks, @jgabitto.🚢

**Pull request merged**
