### PR TITLE
Promote v0.8.0 to Production

### PR DESCRIPTION
**Pull request by mateoclarke**
[Release Notes](https://github.com/cityofaustin/atd-moped/releases/tag/v0.8.0)

[Test Instance](https://moped-test.austinmobility.io/moped/projects)

### CODE REVIEW

**Review by amenity — APPROVED** [review]
Beautiful!! Thanks for all the amazing work, @jgabitto @chiaberry @sergiogcx @johnclary @tillyw @mateoclarke @patrickm02L @janetchuhl !!

Fancy fox

**Review by patrickm02L — APPROVED** [review]
Very excited for this release! Lots of hard work, and really great improvements to Moped. I wholehearted approve! SHIP IT!

**Comment by johnclary** [comment]
@amenity merge dis

**Review by johnclary — APPROVED** [review]

**Comment by amenity** [comment]
Grey-fox-moped

**Pull request merged**
