### PR TITLE
Dropdown order of project roles, status, and phases should match in Gitbook #5857

### PR DESCRIPTION
**Pull request by sergiogcx**
Closes https://github.com/cityofaustin/atd-data-tech/issues/5857

To test:

```
1. Run $ ./hasura-cluster restart
2. Run $ npm run start
```

Check the status order, the roles order, and phase order.

### CODE REVIEW

**Review by mateoclarke — COMMENTED** [review]
I keep getting this error during the seed process:

```
FATA[0025] [postgres-error] query execution failed ($.args[1].args)
[23505] FatalError: duplicate key value violates unique constraint "moped_categories_category_id_key"
Description: Key (category_id)=(2) already exists.
```

**Comment by sergiogcx** [comment]
> I keep getting this error during the seed process:
> 
> ```
> FATA[0025] [postgres-error] query execution failed ($.args[1].args)
> [23505] FatalError: duplicate key value violates unique constraint "moped_categories_category_id_key"
> Description: Key (category_id)=(2) already exists.
> ```

Ah, yikes. Let's take a look 🙏

**Comment by sergiogcx** [comment]
I noticed there were two seed files. I removed the old one and kept the latest, hopefully that should do it.

**Comment by sergiogcx** [comment]
> @sergiogcx New error.
> 
> ```
> FATA[0026] [postgres-error] query execution failed ($.args[1].args)
> [23505] FatalError: duplicate key value violates unique constraint "moped_activity_log_pk"
> Description: Key (activity_id)=(abec9808-f1e9-4b40-85b0-212310b7afc2) already exists.
> ```

I've removed a few bad lines, it runs now in a clean virtual machine:

**Comment by mateoclarke** [comment]
@sergiogcx I got past the seeding errors and that all looks good for the most part but it looks like the order for the project statuses doesn't match [Gitbook order](https://atd-dts.gitbook.io/moped/user-guides/project-status

Screen Shot 2021-04-30 at 1 03 37 PM
)

**Comment by sergiogcx** [comment]
> @sergiogcx I got past the seeding errors and that all looks good for the most part but it looks like the order for the project statuses doesn't match [Gitbook order](https://atd-dts.gitbook.io/moped/user-guides/project-status)

Thanks @mateoclarke got it sorted out, would you review again 😄

**Review by mateoclarke — APPROVED** [review]
🚢  💨

**Pull request merged**
