### PR TITLE
Indicate that an advanced search is active on the "Projects" page

### PR DESCRIPTION
**Pull request by chiaberry**
## Associated issues

The netlify branch has the icon's background color changed if the advanced search is active. Here is the alternative:

Screen Shot 2022-03-03 at 10 58 49 AM

## Testing
**URL to test:** 

[https://8556-active-search--atd-moped-main.netlify.app/moped/projects?](https://8556-active-search--atd-moped-main.netlify.app/moped/projects?filter=eyIzNDA3M2JiMi1mMzk0LTQ3YmUtYWRmNi0xMzZiZWE0MjkwNjkiOnsiaWQiOiIzNDA3M2JiMi1mMzk0LTQ3YmUtYWRmNi0xMzZiZWE0MjkwNjkiLCJmaWVsZCI6InByb2plY3RfdGVhbV9tZW1iZXJzIiwib3BlcmF0b3IiOiJzdHJpbmdfY29udGFpbnNfY2FzZV9pbnNlbnNpdGl2ZSIsImF2YWlsYWJsZU9wZXJhdG9ycyI6W3sib3BlcmF0b3IiOiJfaWxpa2UiLCJsYWJlbCI6ImNvbnRhaW5zIiwiZGVzY3JpcHRpb24iOiJTdHJpbmcgaXMgY29udGFpbmVkIGluIGZpZWxkIChjYXNlLWluc2Vuc2l0aXZlKSIsImVudmVsb3BlIjoiJXtWQUxVRX0lIiwidHlwZSI6InN0cmluZyIsImlkIjoic3RyaW5nX2NvbnRhaW5zX2Nhc2VfaW5zZW5zaXRpdmUifSx7Im9wZXJhdG9yIjoiX2lsaWtlIiwibGFiZWwiOiJiZWdpbnMgd2l0aCIsImRlc2NyaXB0aW9uIjoiRmllbGQgY29udGVudCBiZWdpbnMgd2l0aCBzdHJpbmcgKGNhc2UtaW5zZW5zaXRpdmUpIiwiZW52ZWxvcGUiOiJ7VkFMVUV9JSIsInR5cGUiOiJzdHJpbmciLCJpZCI6InN0cmluZ19iZWdpbnNfd2l0aF9jYXNlX2luc2Vuc2l0aXZlIn0seyJvcGVyYXRvciI6Il9pbGlrZSIsImxhYmVsIjoiZW5kcyB3aXRoIiwiZGVzY3JpcHRpb24iOiJGaWVsZCBjb250ZW50IGVuZHMgd2l0aCBzdHJpbmcgKGNhc2UtaW5zZW5zaXRpdmUpIiwiZW52ZWxvcGUiOiIle1ZBTFVFfSIsInR5cGUiOiJzdHJpbmciLCJpZCI6InN0cmluZ19lbmRzX3dpdGhfY2FzZV9pbnNlbnNpdGl2ZSJ9LHsib3BlcmF0b3IiOiJfaXNfbnVsbCIsImxhYmVsIjoiaXMgYmxhbmsiLCJkZXNjcmlwdGlvbiI6IlNlbGVjdGVkIGZpZWxkIGRvZXMgbm90IGhhdmUgbWVhbmluZ2Z1bCBjb250ZW50IiwiZW52ZWxvcGUiOiJ0cnVlIiwic3BlY2lhbE51bGxWYWx1ZSI6IlwiIDpcIiIsInR5cGUiOiJzdHJpbmciLCJpZCI6InN0cmluZ19pc19udWxsX3NwZWNpYWxfY2FzZSJ9LHsib3BlcmF0b3IiOiJfaXNfbnVsbCIsImxhYmVsIjoiaXMgbm90IGJsYW5rIiwiZGVzY3JpcHRpb24iOiJTdHJpbmcgZmllbGQgZG9lcyBub3QgbWF0Y2ggc3BlY2lhbCBudWxsIHZhbHVlIiwiZW52ZWxvcGUiOiJmYWxzZSIsInNwZWNpYWxOdWxsVmFsdWUiOiJcIiA6XCIiLCJ0eXBlIjoic3RyaW5nIiwiaWQiOiJzdHJpbmdfaXNfbm90X251bGxfc3BlY2lhbF9jYXNlIn1dLCJncWxPcGVyYXRvciI6Il9pbGlrZSIsImVudmVsb3BlIjoiJXtWQUxVRX0lIiwicGxhY2Vob2xkZXIiOiJUZWFtIG1lbWJlciIsInZhbHVlIjoicmVuZWUiLCJ0eXBlIjoic3RyaW5nIiwibGFiZWwiOiJUZWFtIG1lbWJlciJ9fQ==
)

**Steps to test:**

Add an advanced filter, hitting search should keep the icon blue. 

---
#### Ship list
- [x] Code reviewed 
- [x] Product manager approved
- [x] Added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#gid=776973707)

### CODE REVIEW

**Comment by chiaberry** [comment]
This is ready for a style / product review now

**Review by patrickm02L — COMMENTED** [review]
The Filtered by text is overbearing. I suggest the font-color be changed to an accessible light grey like the Header Nav menu.

**Original**
Screen Shot 2022-03-03 at 3 57 43 PM

**Suggestion**
Screen Shot 2022-03-03 at 3 57 15 PM

**Comment by amenity** [comment]
I'm down to use the menu grey. Let's use that variable `Text Secondary` so down the line we can make all of them accessible.

**Review by patrickm02L — APPROVED** [review]
My burning eyeballs have been extinguished!

**Review by frankhereford — APPROVED** [review]
🚀 🚢 👍 

I have reviewed the code and tested the functionality on the netlify deployment linked in the PR description -- looks great, and works perfectly. Thanks Chia!

**Review by mateoclarke — APPROVED** [review]
Looks good! Two suggestions I'd make while we're in this code is adding some padding:


1. seems like the blue circle shouldn't go all the way to the edge of the search box outline.
Screen Shot 2022-03-07 at 3 58 23 PM

3. on either side of the Reset button icon & text
Screen Shot 2022-03-07 at 3 58 39 PM

**Comment by amenity** [comment]
Looks super, thanks, @chiaberry ! I have the hover-circle spacing thing @mateoclarke noted on [this list of design refinements](https://github.com/cityofaustin/atd-data-tech/issues/7402), but I can't replicate the spacing on the reset button. 🤔
Screen Shot 2022-03-07 at 9 27 38 PM

**Review by amenity — APPROVED** [review]
Beautious! 👏 😍 🚢

**Pull request merged**
