### PR TITLE
patch release 2.5.1

### PR DESCRIPTION
**Pull request by chiaberry**
## Associated issues

Primarily I want to fix the bug where the parent project name isnt showing, but also am including the fix to handle undeleting a component. 

https://github.com/cityofaustin/atd-data-tech/issues/15914
https://github.com/cityofaustin/atd-data-tech/issues/15895

--

### CODE REVIEW

**Comment by johnclary** [comment]
🚢 

@chiaberry reminder that these needs a companion PR from this branch in to `main`

**Review by johnclary — APPROVED** [review]

**Review by frankhereford — APPROVED** [review]
Thank you @chiaberry! This is 🚢 🚢 🚀

**Review by mddilley — APPROVED** [review]
🚢

**Review by amenity — APPROVED** [review]
🛵 👪 👍🏻 LGTM,tx!

**Pull request merged**
