### PR TITLE
remove contractor and DO from projects list view and search

### PR DESCRIPTION
**Pull request by chiaberry**
## Associated issues

during QA, it was realized that while the contractor and DO fields were removed from project summary (https://github.com/cityofaustin/atd-data-tech/issues/9770), I didn't remove the columns from the project list view, signals table, or search. This PR removes those columns because they will be out of date and misleading since the contractors are now in the contracts table. 

## Testing
**URL to test:** 
https://deploy-preview-761--atd-moped-main.netlify.app/moped/projects

Here's a test instance link: https://patch-contractor-do-search--atd-moped-main.netlify.app/moped/projects

**Steps to test:**

Cannot add the contractor or Project DO columns to the projects list table, nor search on them. 

---
#### Ship list
- [ ] Code reviewed 
- [ ] Product manager approved
- [ ] Added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#) if applicable

### CODE REVIEW

**Comment by johnclary** [comment]
Noting that he equivalent contractor search functionality won’t be restored until we re-add these columns from the new “Contracts” table ([#10047](https://github.com/cityofaustin/atd-data-tech/issues/10047)).

**Review by mddilley — COMMENTED** [review]
A/B tested with the RC and this deploy preview, and it looks great - I have one question about the project list database view. Should the [contractor and purchase order number](https://github.com/cityofaustin/atd-moped/blob/c2c3d62a92e09e31ef81a2b65e3a97c89a500ee3/moped-database/views/project_list_view.sql#L59-L60) parts of the view be removed before the upcoming work in https://github.com/cityofaustin/atd-data-tech/issues/10047? Or, is that data still used?

**Comment by chiaberry** [comment]
@mddilley it will not be used anymore, the view will need to be updated when the contractor and DO columns are dropped in https://github.com/cityofaustin/atd-data-tech/issues/9770

**Review by mddilley — APPROVED** [review]
Perfect - that makes sense! 🚀

**Review by mateoclarke — APPROVED** [review]
I had the same question as Mike. Sounds good! Thanks for the patch Chia! 🧶

🚢💨✨

**Review by frankhereford — APPROVED** [review]
Looks great! I checked it out on the test deployment and gave the code a read. Thank you @chiaberry! 🚀

**Review by johnclary — APPROVED** [review]
🌬️ ⛵ 🙌

**Pull request merged**
