### PR TITLE
Project View Refactoring

### PR DESCRIPTION
**Pull request by mateoclarke**

### CODE REVIEW

**Review by sergiogcx — APPROVED** [review]
It works! ⚓ 🚢

**Review by mddilley — APPROVED** [review]
Thanks for tidying this up! It is a lot easier to see navigate the project now. 📁 🙌

**Review by amenity — APPROVED** [review]
👍

**Comment by mateoclarke** [comment]
Thanks for the reviews @sergiogcx @mddilley @amenity. 

I had written a nice long updated descriptions of all the things I had addressed in this PR but it was late last Tuesday night and I guess forgot to click the save button 🤦. 

One thing I was excited about that I wanted to make sure y'all see is the updates to the url search parameters for the Project Summary tabs.
 
Screen Shot 2020-12-23 at 2 27 05 AM

Aside from that, most of the things you probably noticed in code review were breaking the project summary view into smaller components and doing some general file/directory reorganization.

**Comment by amenity** [comment]
Oooh -😍  the URL work.

**Pull request merged**
