### PR TITLE
0.7.0 Flicker Ln - Release Candidate

### PR DESCRIPTION
**Pull request by sergiogcx**
[Release Notes](https://github.com/cityofaustin/atd-moped/releases/tag/v0.7.0)

### CODE REVIEW

**Review by johnclary — APPROVED** [review]
All tests passed. Looks splendid to me! Waiting for @patrickm02L and @janetchuhl to review as well.

**Review by janetchuhl — APPROVED** [review]
Found a bug at Map tab: type "Signal" is showing “There are no available subcomponents for this component type.” 

Other than that, everything else looks good!

**Comment by johnclary** [comment]
> Found a bug at Map tab: type "Signal" is showing “There are no available subcomponents for this component type.” 

I believe this is my fault—will provide @sergiogcx with an updated subcomponent mapping.

**Comment by sergiogcx** [comment]
> There are no available subcomponents for this component type

@janetchuhl @johnclary Thank you, and yes. At the moment we mostly do not have subcomponents:

Components table, notice the primary keys:


Current state of subcomponents, only a few components actually have them:

**Comment by johnclary** [comment]
Opened [#6526](https://github.com/cityofaustin/atd-data-tech/issues/6526) to patch the subcomponent records. Sergio doing us a solid!

**Comment by johnclary** [comment]
Confirmed that new subcomponents are available. Product tests have passed. We're off!

**Pull request merged**
