### PR TITLE
Update Moped styles page

### PR DESCRIPTION
**Pull request by jgabitto**
- Closes https://github.com/cityofaustin/atd-data-tech/issues/6737
- Changed page title to Moped Styles
- Change route to `dev/styles`

### CODE REVIEW

**Comment by amenity** [comment]
@jgabitto - can you please update the swatches so there is one for each of these? 

Background Default `#edeeed` 

Background Paper `#ffffff`

Primary Main `#1e88e5`

Primary Dark `#005cb2`

Primary Light `#61b5ff`

Secondary Main `#ff6549`

Text Primary `#212121`

Text Secondary `#848484`

---

Maybe add [a shadow](https://material-ui.com/system/shadows/) to the circles so that the white doesn't disappear?
Screen Shot 2021-07-28 at 3 59 06 PM

**Review by amenity — CHANGES_REQUESTED** [review]
Looking good! Just need those remaining color swatches.

**Comment by jgabitto** [comment]
@amenity Changes have been made!

**Review by amenity — APPROVED** [review]
@jgabitto LSTM!! ✨ 👌🏻 💯

**Review by sergiogcx — APPROVED** [review]
👍 😎

**Pull request merged**
