### PR TITLE
Project Extent | Create project_extent_ids from project_extent_geojson in the front end

### PR DESCRIPTION
**Pull request by mddilley**
Closes https://github.com/cityofaustin/atd-data-tech/issues/5920

This PR updates the code to use `project_extent_geojson` to build the data structure needed to style selected, unselected, and hovered features in the streets and points vector tile layers while editing extent. Previously, the field `project_extent_ids` was used and could potentially become unsynchronized from `project_extent_geojson`. This normalization simplifies the code needed to update a project extent, and it also does not break existing projects in staging that were created with the latest vector tile layers.

To test by creating a new project:
1. Create a a new project at https://deploy-preview-292--atd-moped-main.netlify.app/moped
2. Be sure to enter a random eCapris ID since the patch has not been merged to staging yet
3. Select some features for the project extent and save
4. Ignore the "cannot map undefined error" because this branch is not up-to-date with main
5. Find your project in the Projects view and test out editing the extent

To test on an existing project:
1. Go to https://deploy-preview-292--atd-moped-main.netlify.app/moped/projects/224

### CODE REVIEW

**Review by sergiogcx — APPROVED** [review]
Thanks for working on this!

**Comment by sergiogcx** [comment]
@mddilley Everything looks good, the only real comment I have is that this branch is behind main a little bit so whenever I tried to create a new project given the ecapris error. Just making sure we don't introduce old bugs into main.

**Comment by mddilley** [comment]
Thanks for the quick review, @sergiogcx. I will be sure to pull `main` through the trail of branches leading up to this PR and resolve any conflicts. Also, I'll hold off on merging anything until after the current release. Sorry for the mess! 😅 🙏

**Review by mateoclarke — APPROVED** [review]
its_magic

**Pull request merged**
