### PR TITLE
Fix dark background bug

### PR DESCRIPTION
**Pull request by jgabitto**
- Closes https://github.com/cityofaustin/atd-data-tech/issues/6779
- Removes background color dark prop from styles in Not found view, Dashboard, and Fallback summary map

### CODE REVIEW

**Comment by amenity** [comment]
@jgabitto - the dark background color is still overriding the default background color: 
Screen Shot 2021-07-28 at 2 52 43 PM

**Comment by amenity** [comment]
I have no idea why it would still be there since you removed it from the theme??

**Review by amenity — APPROVED** [review]
So fresh & clean! Thankssssss, @jgabitto

**Review by sergiogcx — APPROVED** [review]
🙏💡 🚢

**Comment by chiaberry** [comment]
Ha that gif Sergio brings back literal flashblacks of overhead projectors

**Pull request merged**
