### PR TITLE
Reroute user to moped staff page after a staff member is deleted

### PR DESCRIPTION
**Pull request by jgabitto**
- Closes https://github.com/cityofaustin/atd-data-tech/issues/6475
- Add navigate to callback after user is deleted in staff view
- User is redirected to '/moped/staff/' 

**How to test**
- Visit website using the netlify build preview.
- Make sure your moped account has the ability to delete users.
- Visit staff page and select a user you want to delete.
- Afterwards click the delete user button and then confirm.

### CODE REVIEW

**Review by sergiogcx — APPROVED** [review]
Ah, cool. Glad it turned out a lot easier than anticipated. It works perfectly btw,

**Review by mateoclarke — APPROVED** [review]
🚢

**Comment by amenity** [comment]
The first time I tried deleting Leslie's account and it spun forever but when I navigated back to the "Staff" page she was gone. 

I tried repeating with Amica (who had a Mike D. email) and a similar thing happened. I refreshed the page, tried to delete again, got an error, and manually went back to the "Staff" page. It looks like she was removed. 🤔

@mateoclarke @sergiogcx - were y'all testing on Netlify?

https://user-images.githubusercontent.com/1463708/127941138-33883a31-48e7-408c-b5c4-1a51c19c462b.mov

**Comment by mateoclarke** [comment]
Yeah @amenity I was seeing a similar issue when testing on staging. Sergio changed my user from admin to viewer and then back to admin, essentially toggling the permissions to reset my credentials and that seemed to fixed it. But I don't understand why. Cognito is a black box to me.

**Comment by amenity** [comment]
Cool, good to know, @mateoclarke. @sergiogcx @jgabitto  - if what I'm seeing is to be expected, I'm good to merge!

**Comment by jgabitto** [comment]
@amenity @mateoclarke @sergiogcx How come there have been issues? Is there something I should change?

**Comment by sergiogcx** [comment]
@jgabitto the issues are not related to the javascript you wrote, it's around the permissions to delete and conflicts between environments. Your code works perfectly, and I would suggest you merge them. I will work with y'all to have your permissions extended or double-checked if needed.

**Comment by sergiogcx** [comment]
@amenity @mateoclarke @jgabitto also happy to answer any questions you have or to work out whatever issues you are encountering...

**Comment by amenity** [comment]
Thanks, @sergiogcx @jgabitto. Tried it out on staging and seeing some strange behavior: 

https://user-images.githubusercontent.com/1463708/128064623-0b5f15a4-42e9-433f-a000-164ad8ff5162.mov

I recorded this in Incognito, with a fresh log in and empty cache.

**Pull request merged**
