### PR TITLE
Creates project milestone table to add/edit milestones

### PR DESCRIPTION
**Pull request by tillyw**
Adds Milestones table, allowing user to add, update and delete milestones

This PR includes database changes, so may require a test instance or to be run locally to test.

https://user-images.githubusercontent.com/35410637/119046498-610c1180-b982-11eb-9ff4-05699793edb9.mov

### CODE REVIEW

**Review by amenity — APPROVED** [review]
Looks beautiful, @tillyw ! ✨ 📅

**Comment by amenity** [comment]
PS I created this issue. We'll see if any _actual_ users _actually_ need it... ;)

**Review by mateoclarke — APPROVED** [review]
milestones

Works great Tilly!

**Comment by tillyw** [comment]
> milestones
> 
> Works great Tilly!

Awesome, thanks Mateo!

**Pull request merged**
