### PR TITLE
Editor | Show inactive/active status in User table and update seed with workgroups

### PR DESCRIPTION
**Pull request by mddilley**
#### Updated User table status
Screen Shot 2020-12-04 at 3 55 10 PM

#### Updated workgroup dropdown populated from seed data
Screen Shot 2020-12-04 at 5 03 10 PM

### CODE REVIEW

**Review by mateoclarke — APPROVED** [review]
🚢

**Comment by mateoclarke** [comment]
I may have said ship it too soon. Guess we'll need to rerun the seed in staging and prod too maybe?

Screen Shot 2020-12-08 at 5 21 53 PM

**Comment by mddilley** [comment]
Good catch @mateoclarke - I'm seeing the same error in staging https://moped.austinmobility.io/moped/staff. Looks like there is an issue with the users aggregate in the staging Hasura instance.
Screen Shot 2020-12-08 at 5 38 33 PM

**Comment by sergiogcx** [comment]
Ah, shoot we just have to add aggregate query permissions to that role for that user.

**Comment by mateoclarke** [comment]
This looks good but it looks like the deploy preview app cancelled mid-deployment so I didn't test it on staging.

**Review by mateoclarke — APPROVED** [review]
this_is_the_way_2

**Review by sergiogcx — APPROVED** [review]
This is excellent, thank you!

**Pull request merged**
