### PR TITLE
[Bug] File uploads do not show in the activity log #5544

### PR DESCRIPTION
**Pull request by sergiogcx**
Closes https://github.com/cityofaustin/atd-data-tech/issues/5544

Live Demo:
https://5544-sg-fileuploads-activitylog--atd-moped-main.netlify.app/moped/projects/164?tab=activity_log

Look! The file uploads are showing nicely:

### CODE REVIEW

**Review by mddilley — APPROVED** [review]
Tested on your example, and it works great! :a🙌

**Review by mateoclarke — APPROVED** [review]
This looks really good! 🚢  

Just wanted to note that when I deleted my test file on the project you linked in your description, the Activity Log shows it as an update to the project file from deleted "false" to "true". I expected it to show as Deleted with the close icon based on your code, but not sure how much this edge case matters right now.

**Comment by sergiogcx** [comment]
Thank you for catching that @mateoclarke , I need to make sure it shows Deleted as opposed to Updated. That's kind of confusing.

**Review by amenity — APPROVED** [review]
Second @mateoclarke's comment, but other than that...✨ LSTM!✨

**Pull request merged**
