### PR TITLE
Collapse sidebar menu at all viewport sizes

### PR DESCRIPTION
**Pull request by johnclary**
Closes [#6190](https://github.com/cityofaustin/atd-data-tech/issues/6190).

navbar

### CODE REVIEW

**Comment by johnclary** [comment]
As I mentioned in sync—we should tackle the Avatar nesting separately. See [#6145](https://github.com/cityofaustin/atd-data-tech/issues/6245).

**Review by amenity — APPROVED** [review]
# 😍 
Soooo beautiful. Gosh this makes a huge difference.

**Comment by amenity** [comment]
@johnclary - I wonder if the moped ---> all projects is discoverable enough or whether we should add a breadcrumb to get the user back to the project listing 
Screen Shot 2021-05-28 at 4 54 12 PM

**Comment by johnclary** [comment]
Yep—I agree. I'd stick your screenshot into [#5227](https://github.com/cityofaustin/atd-data-tech/issues/5227) and queue it up once Chia's URL params work is done.

**Review by chiaberry — APPROVED** [review]

**Pull request merged**
