### PR TITLE
Add array relation from moped_proj to moped_proj_partners

### PR DESCRIPTION
**Pull request by johnclary**
## Associated issues
Fixes [#8441](https://github.com/cityofaustin/atd-data-tech/issues/8441)

This is purely a Hasura config change to simplify Knack migration mutations.

## Testing
**URL to test:** TBD: need to deploy to test env

**Steps to test:**
Make sure project partners still works as expected
1. Go to project summary tab
2. Add a project partner
3. Remove a project parter

---
#### Ship list
- [ ] Code reviewed 
- [ ] Product manager approved
- [x] Added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#gid=776973707)

### CODE REVIEW

**Comment by johnclary** [comment]
I haven't deployed to test but it's ready to be deployed at any time.

**Comment by johnclary** [comment]
i'm merging this into the RC so that I can finish the migration preview on staging.

**Review by frankhereford — COMMENTED** [review]
It's database relations all the way down. Can you imagine a world where `graphql-engine` is a dumb HTTP server on top of a PostgreSQL extension, a la PostGIS.

Thanks for making this PR 🙏 .

**Review by mateoclarke — COMMENTED** [review]
👍

**Pull request merged**
