### PR TITLE
Skip version check in `hasura` CLI in Github actions

### PR DESCRIPTION
**Pull request by frankhereford**
## Associated issues

This PR intends to close https://github.com/cityofaustin/atd-data-tech/issues/8622. 

## Testing

Testing is sort of free on this one. Deploying this to the `test` instance and subsequent deployments to `staging` and `production`, if successful, should be considered an acceptable test. 

- [x] Deploy to `test`

---
#### Ship list
- [x] Code reviewed 
- [x] Product manager approved
- [ ] ~Added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#gid=776973707)~

### CODE REVIEW

**Review by chiaberry — COMMENTED** [review]
could we also get the flag set in the hasura-cluster commands?  L351

**Comment by frankhereford** [comment]
@chiaberry wrote:
> could we also get the flag set in the hasura-cluster commands? L351

@mateoclarke and I posted some quick notes on the issue about this, and he suggested that we might leave it as a reminder that we're slipping away from current versions, which I'm inclined to agree with. What do you think is best? Nothing is set in stone, for sure.

One thing we can do individually though is update the CLI version installed on our laptops' OS, which will accomplish both suppressing the notice message _and_ testing out updated CLI tools with our v.1.3.3 instance. That's why I'm doing, and it's worked so far, although, I've only spun up and down the DB a few times.

**Review by amenity — APPROVED** [review]
Thanks, Frank!

**Comment by chiaberry** [comment]
Makes sense to me! I retract my comment

**Review by mateoclarke — APPROVED** [review]
Skip it! 🚢 💨 ✨ 

skip_it

**Pull request merged**
