### PR TITLE
Refactor use of ProjectSummaryMap & Fallback to eliminate console errors

### PR DESCRIPTION
**Pull request by frankhereford**
## Associated issues

This PR intends to close [#7808](https://github.com/cityofaustin/atd-data-tech/issues/7808).

This commits in this PR have been cherry-picked from #470, where you may find the original discussion around these changes.

## Testing
**URL to test:** https://deploy-preview-473--atd-moped-main.netlify.app/

**Steps to test:**

- [ ] Use the landing page for a project and observe console for errors.

---
#### Ship list
- [ ] Code reviewed

### CODE REVIEW

**Review by mateoclarke — COMMENTED** [review]
This logic makes sense to me but I'm still seeing a lot of noise in the dev console on the Project Summary page coming from the `ProjectSummaryMapFallback` component so I'm not sure if all the errors are being eliminated. 

Also noticed a bug where if you add components to a project with no map features, the Summary page doesn't render the map with the newly added component(s) without a hard page refresh. This may or may not be related to this PR, but I do want to make sure it's not a regression. 

Maybe we can walk through this one together as well Frank?

**Comment by amenity** [comment]
@mateoclarke - does this cover that bug? https://github.com/cityofaustin/atd-data-tech/issues/7403

**Comment by frankhereford** [comment]
> This logic makes sense to me but I'm still seeing a lot of noise in the dev console on the Project Summary page coming from the `ProjectSummaryMapFallback` component so I'm not sure if all the errors are being eliminated.
> 
> Also noticed a bug where if you add components to a project with no map features, the Summary page doesn't render the map with the newly added component(s) without a hard page refresh. This may or may not be related to this PR, but I do want to make sure it's not a regression.
> 
> Maybe we can walk through this one together as well Frank?

For sure! I'm really curious to see what errors are still coming through. This PR only is really aimed at a single JS error, so I'm curious if it's that same one persisting or another. Either way of course, I'm looking forward to discussing it when you're available. 

I also am looking forward to learning more about the hard-refresh requirement, and I'm very confident that this is unrelated, but I'd like to learn about what is or was going on with that. 

Thanks!

**Comment by frankhereford** [comment]
> This logic makes sense to me but I'm still seeing a lot of noise in the dev console on the Project Summary page coming from the `ProjectSummaryMapFallback` component so I'm not sure if all the errors are being eliminated.

@mateoclarke - Mystery solved! In PR #470, I had a particular commit `11ff548c` which changed the logging method used on the `console` object in ProjectSummaryMapFallback. When I was asked to split #470 into two seperate PRs (#472 & #473), I put that commit in #472, as it seemed to belong with the other adjustments to our usage of the `console` object. It turns out, it really was serving a dual role, both as a console noise clean-up, but also as part of the refactoring of the way we use and error handle in ProjectSummaryMapFallback. 

I have cherry picked that commit into this branch for the sake of clarity, and it will just turn be a non-change if/when we merge this PR into main.

Thanks again for bringing the unexpected behavior to my attention!

**Comment by chiaberry** [comment]
@mateoclarke @amenity I can confirm that behavior you described Mateo isn't a regression, its happening in main right now. The issue Amenity linked covers the bug imo.

**Review by mateoclarke — APPROVED** [review]
Re-tested locally and some noise in the console has been reduced! 🚢 💨 ✨ 

bobba

**Comment by frankhereford** [comment]
I plan on merging this in after our upcoming meeting unless we discuss otherwise. 

FYI: There is no review from product; Amenity indicated that she felt it wasn't needed here. @amenity - if I'm not explaining that well, please correct me!

Thanks!

**Pull request merged**
