### PR TITLE
Adds a secret view of moped phases and milestones

### PR DESCRIPTION
**Pull request by johnclary**
## Associated issues
Hoping to replace [this spreadsheet](https://docs.google.com/spreadsheets/d/13EbvdJNoZRCXQOJZJdrUqTUb2-o2puMXhiZN_94_go0/edit#gid=217441231) in service of https://github.com/cityofaustin/atd-data-tech/issues/9593.

 Depends on https://github.com/cityofaustin/atd-moped/pull/716.

## Testing
**URL to test:** Moped test or local.

**Steps to test:**
1. Navigate to `/moped/dev/lookups`
2. Tables with `moped_phases`and `moped_milestones` should render.

Screen Shot 2022-07-14 at 2 13 27 PM

Screen Shot 2022-07-14 at 2 13 35 PM

---
#### Ship list
- [ ] Code reviewed 
- [x] Product manager approved
- [ ] Added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#) if applicable

### CODE REVIEW

**Review by amenity — APPROVED** [review]
I know this is still WIP, but 😍 .

**Comment by johnclary** [comment]
@amenity this no longer WIP unless you've got feedback for it. we could add more tables, like from [this workbook](https://docs.google.com/spreadsheets/d/1LaAfo3MEiiFZ1pReTQRJYxh9mUg3nZVm5TbNju9K16c/edit?usp=sharing) chia put together. if we do that, we probably need a nav. maybe tabs?

**Comment by amenity** [comment]
@johnclary - let's throw this up and make a backlog issue for extending it. ✔️

**Review by chiaberry — APPROVED** [review]

**Review by mddilley — APPROVED** [review]
Works and looks great! The only reason that I can think of to use material-table is for the .csv export OOTB, but that can always come down the line. And, I honestly don't know if that is needed for this use case.

**Comment by johnclary** [comment]
thanks y'all!

**Pull request merged**
