### PR TITLE
Add detection and support for M1 ARM64 architecture to moped-database

### PR DESCRIPTION
**Pull request by frankhereford**
## Associated issues

This PR intends to close [#7810](https://github.com/cityofaustin/atd-data-tech/issues/7810).

## Testing
Follow the normal instructions to spin up the database on either platform and verify that it works for you.
- [x] X86_64
- [x] ARM64

### PostgreSQL server image
~* I have increased the amount of time that the cluster has to start before the `hasura-cluster` script executes migrations, metadata and seeds from 60 seconds to 120 seconds. The cluster starts slower now because it's running via the qemu emulation layer, but once it's running, the performance appears to be nominal. If Hasura were to start to ship multi-platform images, this would become a non-issue.~

* I have switched the postgres image over to a native build for arm64. I built this today using the postgis docker build repo without modification; it's super easy. This results in database rebuild times being reduced to 25% of the original duration for me when testing the VZ DB (which has millions of records.) For Moped, the database size is still small, so that's not an issue, but cluster start-up times are cut in half if not more. At the time of writing, a cluster spin up takes 1 minute and two seconds (1:02.54) of wall time on this computer. 🕐 

### graphql-engine image
~* I have also built the graphql-engine v1.3.3 from source personally, and the image can be found [here](https://hub.docker.com/repository/docker/frankinaustin/graphql-engine-arm64).~

* There was group consensus to use `fedormelexin`'s build of `graphql-engine` v1.3.3, however, I would like to propose that we stick with my build. I have zero reason to believe that Fedor's build isn't completely fine; it's that I have used mine personally for development for a few months now and it has performed without a single issue. It's just the only one of the two that I have personal experience with, and it's totally solid. 🪨 

---
#### Ship list
- [ ] Code reviewed

### CODE REVIEW

**Review by sergiogcx — CHANGES_REQUESTED** [review]
@amenity @patrickm02L @mateoclarke 

Did any of you request this change? I don't see an issue for this one. This PR is unnecessary as per [docker's documentation for Apple M1](https://docs.docker.com/desktop/mac/apple-silicon/): "Docker Desktop for Apple silicon [...] allows you to build and run images for both x86 and ARM architectures without having to set up a complex cross-compilation development environment".

1. [PostGIS does not have any ARM images](https://registry.hub.docker.com/r/postgis/postgis/tags?page=1) yet it runs fine in M1 without any modifications, why make the modifications for hasura?
2. It looks like the reported error in hasura is exit code 137, which indicates sigkill (out of memory).
3. Other devs in hasura report being able to run it in M1 by just [increasing the memory limit from 2gb (default) to 6gb](https://github.com/hasura/graphql-engine/issues/1266#issuecomment-770824766).
4. Do we know who `fedormelexin` is? Using unknown images is a cybersecurity risk, we should only be using images from reputable sources because we just don't know what they contain or how they were built. Here is a good article that explains more about this. https://blog.aquasec.com/docker-official-images

**Comment by johnclary** [comment]
I asked Frank to do the leg work to identify next steps for running our containers on the M1, since we will be phasing those new Macs into our team. Opening a PR is a fine way to begin that discussion—and we can continue it as a team. Let's leave this open for now and thanks @frankhereford for spending your weekend on this.

**Review by mateoclarke — APPROVED** [review]
I talked with Frank today about this PR. He explained that there are hurdles in his local dev environment to accommodate for the M1 chip that this PR was intended to address. The updates to the docker files look good and tested ✅ for me locally. Frank also explained how he built a new image and published it to [docker hub](https://hub.docker.com/r/frankinaustin/graphql-engine-arm64) to address the security concern. 

I feel like we can merge this now and continue iterating if needed as we learn more and as other trusted images get developed in the community. ✨

**Comment by frankhereford** [comment]
@sergiogcx - I hope you're doing well today. I would like to merge this into main today if possible. I have add provided a docker image with the graphql-engine compiled from source to address the 4th point in your comment above. Would you be willing to release the "Changes Requested" status of your review to allow me to merge this?

**Comment by sergiogcx** [comment]
@mateoclarke @frankhereford we shouldn't merge just yet. Thank you for addressing item no. 4, but we have addressed the other questions in the issue. On top of that, if we do decide (as a team) we want to begin building ARM images, I have more questions that have not yet been addressed. I haven't been invited to your discussions and had no chance to ask.

**Comment by frankhereford** [comment]
> @mateoclarke @frankhereford we shouldn't merge just yet. Thank you for addressing item no. 4, but we have not addressed the other questions in the issue. On top of that, if we do decide (as a team) we want to begin building ARM images, I have more questions that have not yet been addressed. I haven't been invited to your discussions and had no chance to ask.

Understood - I will hold off on merging until that consensus is reached. Thanks.

**Comment by sergiogcx** [comment]
Just documenting my homework, this is running Hasura 1.3.3 amd64 image, this is a virtual mac mini m1 with 8gb ram:






Building on GitHub with qemu's extension times out at 6 hours:

**Comment by frankhereford** [comment]
@sergiogcx @johnclary @mateoclarke

Thank you each for your time this afternoon to meet and discuss the pros and cons of various approaches related to the M1 ARM64 architecture and Moped. I wanted to capture the action items and big-picture ideas that we agreed upon.

1) By-and-large, Intel images can be run on M1, but doing so comes at a performance cost. Sergio noted a marked increase of RAM usage, and I have found the same postgis image to take >10X the time to reload the VZ database as another example of the price of emulation.
1) Because of the tradeoffs between running a widely-used, but emulated image versus a natively compiled but not widely used image will shift over time, it would be helpful for those who are using M1 chips to be able to specify if they want to use Hasura's Intel image vs. Fedor Melekhin's ARM image. The group agreed that this should be done via an argument to the `hasura-cluster` cluster management tool.
    * I propose that it also should be able to also be optionally defined in the configuration file that `hasura-cluster` uses. If it's defined in the configuration file and also specified via argument by the user, the `hasura-cluster` should follow the argument's instruction. Do you all like this approach?
    * Frank will implement the additional functionality needed above. 
1) Having taken a deep dive into Fedor's build process and his history of making timely releases of ARM builds, the group agreed that he can be considered a trusted source of images to use in our shop.

That's all I wrote down -- is there anything else that I missed? Thanks again y'all - that was a really interesting conversation!

**Comment by frankhereford** [comment]
Thanks @chiaberry for testing the database related changes today on `x86-64`. She indicated that the `hasura-cluster` changes and related reorganization of the docker-compose files functioned as intended.

**Comment by frankhereford** [comment]
Closing this in deference to [#537](https://github.com/cityofaustin/atd-moped/pull/537).

**Pull request closed without merging**
