### PR TITLE
Add Signage - All Way Stop component type

### PR DESCRIPTION
**Pull request by mddilley**
## Associated issues
Closes https://github.com/cityofaustin/atd-data-tech/issues/19747

This PR adds a component type named **Signage - All Way Stop** and its associated work types.

## Testing
**URL to test:** 

Local

**Steps to test:**
1. Start up your local stack and test creating a new intersection component called **Signage - All Way Stop**
2. See that **New** is the only available component work type
3. When mapping the component, you should see that it selects from the intersections point layer.

---
#### Ship list
- [x] Code reviewed 
- [x] Product manager approved
- [x] Product manager checked [DB view dependencies](https://atd-dts.gitbook.io/moped-documentation/product-management/updating-the-arcgis-online-components-database-view)
- ~[ ] Product manager added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#) if applicable~

### CODE REVIEW

**Review by johnclary — APPROVED** [review]
Migrations check out, and I was able to add the new signage component.

I noticed the generic **Signage** component has the modification and maintenance/repair work types. Not sure if you want to add those to this fella:

Screenshot 2024-11-19 at 9 00 48 AM

🚢 🚢 🚢 🚢  🛑

**Review by chiaberry — APPROVED** [review]
🛑  all way!

which I mean to say 🚢

**Comment by mddilley** [comment]
@johnclary thanks for checking in on that, and I had the same inclination but the request was specific about `New` only being needed after presenting our menu of options.🍴 We'll see...

**Review by roseeichelmann — APPROVED** [review]
:ship: looks good!

**Comment by tillyw** [comment]
i'm getting an apollog error when i try to save a new All Way Stop component but this may be because I am using seed data

Screenshot 2024-11-20 at 6 25 04 PM

**Review by tillyw — APPROVED** [review]
tested using prod data and it worked!

**Pull request merged**
