### PR TITLE
Project Extent | Implement Project Extent mapping features

### PR DESCRIPTION
**Pull request by mddilley**
Closes https://github.com/cityofaustin/atd-data-tech/issues/4619
Closes part of https://github.com/cityofaustin/atd-data-tech/issues/4700

This PR updates the New Project map with:

- Fix Mapbox basemap in staging (currently getting a 403 for tiles)
- Zoom ➕ and ➖
- Address search (added [react-map-gl-geocoder](https://github.com/SamSamskies/react-map-gl-geocoder))
- Modify default ~map center~ zoom so that more of the map is visible on load
- Preserve polygons selected on map in state at `NewProjectView` component level

#### Map zoom controls, address search, and updated zoom
Screen Shot 2020-12-15 at 1 58 41 PM

#### Save selected polygon in state when navigating between steps
persistPolygons

### CODE REVIEW

**Comment by amenity** [comment]
Splendid, @mddilley!✨ 🗺️

**Review by amenity — APPROVED** [review]
Beautiful! 🌟

**Comment by amenity** [comment]
Chatted w/ Mike about an enhancement to r[estrict the geocoder results to the Moped "region"](https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-geocoder-limit-region/)... Only ... I don't know how to define it. 😅

**Review by sergiogcx — APPROVED** [review]
It works great, thank you @mddilley !

**Review by mateoclarke — APPROVED** [review]
Excellent stuff @mddilley 

kobe_10

**Pull request merged**
