### PR TITLE
Combine multiple advanced filters for same field

### PR DESCRIPTION
**Pull request by chiaberry**
All changes happen in atd-kickstand: https://github.com/cityofaustin/atd-kickstand/pull/8

For testing and development I pulled the GQL Abstract file into moped. If you check the kickstand PR linked above, you can see the changes made the the GQLAbstract class. Once the kickstand PR is approved, I'll close this one. 

https://deploy-preview-342--atd-moped-main.netlify.app/

I tested stacking dates (less than 6/1/2021, greater than 3/1/2021), tested multiple project names (contains "john", contains "test")

### CODE REVIEW

**Review by sergiogcx — CHANGES_REQUESTED** [review]
We cannot have the GQLAbstract inside of Moped, go ahead and create a PR that updates the kickstand library:

https://github.com/cityofaustin/atd-kickstand/tree/main/src/graphql

**Comment by chiaberry** [comment]
@sergiogcx , the PR for kickstand is linked this this PR's description. I thought I had added you as a reviewer for that PR, but I just checked and it only had mateo listed. Added you now.

**Review by sergiogcx — APPROVED** [review]

**Comment by sergiogcx** [comment]
It woks great! Thanks! 🙏

**Review by amenity — APPROVED** [review]
Nice! 
Screen Shot 2021-06-11 at 4 41 51 PM

**Pull request merged**
