### PR TITLE
Add new project tags to help track SS4A grant funding (Patch into main)

### PR DESCRIPTION
**Pull request by mddilley**
## Associated issues
Moving the patched changes from https://github.com/cityofaustin/atd-moped/pull/1508 into `main`

## Testing
**URL to test:** 

Local

**Steps to test:**
1. Same as https://github.com/cityofaustin/atd-moped/pull/1508

---
#### Ship list
- [x] Code reviewed 
- [x] Product manager approved
- [x] Product manager checked [DB view dependencies](https://atd-dts.gitbook.io/moped-documentation/product-management/updating-the-arcgis-online-components-database-view)
- ~[ ] Product manager added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#) if applicable~

### CODE REVIEW

**Review by frankhereford — APPROVED** [review]
@mddilley what do you think about the policy that if you get approval on a PR that is part of a patch, you can use that authority for the second PR that gets it into the other branch? 

Like -- I think you should only need a checkmark on this to get your button green and then you're good to go. This second approval should come for free to you.

**Comment by mddilley** [comment]
@frankhereford I'm okay with keeping our normal review process for both PRs just in case I made a silly mistake with the cherry-picking or target branch or something. I've definitely done something like that before! 🙃

**Comment by frankhereford** [comment]
@mddilley wrote:

>  in case I made a silly mistake 

Smart -- goodness knows i have too, many many times.

**Comment by chiaberry** [comment]
ha, I thought we already had that policy....

**Pull request merged**
