### PR TITLE
Update activity log order in query instead of UI

### PR DESCRIPTION
**Pull request by mateoclarke**
Alternative approach to cityofaustin/atd-data-tech#5599

### CODE REVIEW

**Comment by tillyw** [comment]
@sergiogcx We were wondering if there is a particular need for a logical statement that isolates the "creation" event and puts it first (or last in this iteration). Do you think the same would be accomplished by ordering by `created_at` in the query, or is there something we're missing?

**Comment by sergiogcx** [comment]
@tillyw @mateoclarke yes, the additional logic is needed because the events arrive at different times. Whenever a new project is created we are also creating personnel records and phases records, those are separate events and they arrive at unpredictable times to the database activity log. So I added additional logic to separate the create event for the project and move it to the top.

**Comment by sergiogcx** [comment]
To follow up on the previous comment I made, here is the code that selects the INSERT event for an object of type moped_project: 

https://github.com/cityofaustin/atd-moped/blob/f6a45b10939831e977075b75b0c97b09869e1299/moped-editor/src/views/projects/projectView/ProjectActivityLog.js#L139

**Comment by mateoclarke** [comment]
ok, thanks Sergio, I'll update this PR.

**Pull request closed without merging**
