### PR TITLE
Project Extent | Implement refinements to "Map project" step in new project workflow and "Project summary" page

### PR DESCRIPTION
**Pull request by mddilley**
Closes https://github.com/cityofaustin/atd-data-tech/issues/5376

This PR makes the following updates: 

1. Require at least one line selected (used this MUI pattern https://material-ui.com/components/steppers/#non-linear-error-step)
2. Sentence case in "Map project"
3. Remove "Polygon ID" hover
4. Set map extent to match to project extent when edit panel opens

### New Project stepper warns and disables submission if no features selected in map
validateLocation

### Map fits to feature collection on edit
zoomOnEdit

### Map fits to feature collection in new project stepper
zoomInStepper

### Sentence case
sentenceCaseMap

### CODE REVIEW

**Review by amenity — COMMENTED** [review]
✅ New Project stepper warns and disables submission if no features selected in map
✅ Map fits to feature collection on edit
✅ Map fits to feature collection in new project stepper
✅ Sentence case


The [error-step](https://github.com/cityofaustin/atd-moped/pull/232/files#submit-review) looks really slick. 😎 I didn't see it at first and expect that users might miss it as well, so we might want to implement an additional warning closer to the "Finish" button. 

I am getting a bug where when I delete all the segments from a project, the map view on the Project Summary page does not update at the same time:


https://user-images.githubusercontent.com/1463708/110227059-f5092980-7eb9-11eb-9f3b-af26459fa34e.mov

**Review by mateoclarke — APPROVED** [review]
The code looks really good. I was able to reproduce the bug emoji caught. It looks like the state of the `featureCollection `objects in the view-only and edit-mode version gets out of sync when there is an empty `featureCollection` saved. I followed Amenity's steps and then clicked the Edit button and when you get back in the edit mode, the lines I had deleted were not selected.

All this said, this seems like it could be hairy to resolve and seems like an edge case in practice. I'd be ok if we backlog this bug and merge this PR as is. If @amenity is too.

**Comment by amenity** [comment]
Yup! I’m good to merge and backlog the bug.

**Comment by mddilley** [comment]
@amenity @mateoclarke Thanks for review and catching/reproducing that bug! 🙏  I'll take a quick look at it but will create an issue if it is will take too much time. I'll merge this today either way.

**Comment by mddilley** [comment]
@amenity @mateoclarke Thanks for review and catching/reproducing that bug! 🙏  I'll take a quick look at it but will create an issue if it is will take too much time. I'll merge this today either way.

**Pull request merged**
