### PR TITLE
Add additional workgroups to Moped #6768

### PR DESCRIPTION
**Pull request by sergiogcx**
Closes https://github.com/cityofaustin/atd-data-tech/issues/6768

** MIGRATIONS ONLY:  These can only be tested in **moped-test** or local.

Changes:

Additional workgroups to moped_workgroup table

For Public Works:
- Urban Trails
- Safe Routes to School
- Corridor Program Office
- Sidewalks
- Engineering Services Division

New table, moped_department:
- Austin Transporation
- Corridor Program Office
- Public Works

- Moped Workgroup has a new column department_id, and it has associated relationships

A user can be filtered or grouped by department:

### CODE REVIEW

**Review by chiaberry — APPROVED** [review]

**Comment by mateoclarke** [comment]
This is less of a question for @sergiogcx and his implementation and more of a question for @amenity about the feature specs. Just want to make sure that its intentional for there to be a "Corridor Program Office" workgroup that belongs to the "Public Works" department and a "Corridor Program Office" department that has no workgroups at all.

Screen Shot 2021-08-02 at 9 44 21 PM
Screen Shot 2021-08-02 at 9 46 15 PM

**Review by mateoclarke — APPROVED** [review]
Assuming my question about the intention of the feature is resolved by @amenity... 🚢

**Review by amenity — APPROVED** [review]
All the workgroups are there!👍

Unfortunately, I see that the original [issue description](https://github.com/cityofaustin/atd-data-tech/issues/6768) was confusing. It had a typo with "Corridor Program Office" under Public Works. _Plus,_ I'd missed "Other" when I said in Slack that all the existing workgroups belong to ATD.🤦‍♀️   So sorry, @sergiogcx  😞


I re-wrote it for better clarity and pasting here as well...

---
Create new table, `moped_department`
- Austin Transporation
- Corridor Program Office
- Public Works
- Other

Add lookup column to `moped_workgroup` to connect with `moped_department`.
- All the existing workgroups are in Austin Transportation

Add additional workgroups to `moped_workgroup` table and associate all workgroups to departments

**Public Works** department workgroups:
   - Urban Trails 
   - Safe Routes to School
   - Sidewalks
   - Engineering Services Division 

**Corridor Program Office** department workgroups:
   - Corridor Program Office

**Austin Transportation** department workgroups:
   - ([All existing workgroups](https://user-images.githubusercontent.com/1463708/127951609-e57974a6-d46a-4cab-82f1-cd50b3e5e045.png), besides "Other")

**Other** "department" workgroups:
   - Other

**Comment by amenity** [comment]
So, to summarize how to resolve: 
- [ ] In the `moped_department` table, add a 4th department, "Other" with `department_id` of "4"
- [ ] In the `moped_workgroup` table, change the `department_id` of "Other" to "4"
- [ ] In the `moped_workgroup` table, change the `department_id` of "Corridor Program Office" to "2"

table

Again, all my fault with the sloppy issue description. 😞

**Comment by sergiogcx** [comment]
Got it, np! :)

**Pull request merged**
