### PR TITLE
Make use of user initials in the account page

### PR DESCRIPTION
**Pull request by sergiogcx**
This is what it should look like now:

https://deploy-preview-215--atd-moped-main.netlify.app/

### CODE REVIEW

**Review by amenity — APPROVED** [review]
Looks great!

**Comment by mateoclarke** [comment]
@sergiogcx, Looks good for the initials/avatar fix. I'm wondering if we should've replaced the user's first/last name with their email. Was that a request from Product Team? Shouldn't it be possible to make the association between the cognito user and the moped_user table

**Review by mateoclarke — COMMENTED** [review]
🚢

**Comment by sergiogcx** [comment]
There are three ways to do that, one is to extend the token a little bit, another is to retrieve data via API, another is to retrieve data via GraphQL. Happy to discuss,

**Pull request merged**
