### PR TITLE
Include moped version number in footer

### PR DESCRIPTION
**Pull request by chiaberry**
closes https://github.com/cityofaustin/atd-data-tech/issues/6520

https://deploy-preview-358--atd-moped-main.netlify.app/moped

the netlify sidebar icon slightly covers the footer. What do yall think of the color of the text and the size? Margin/padding?

### CODE REVIEW

**Comment by sergiogcx** [comment]
I apologize for not updating the version number for the 0.7.0 release, I will be patching that shortly. I love the link to the release notes. I wonder if we should also have the DTS team link and style of the VisionZero footer:

**Review by patrickm02L — APPROVED** [review]
Nice. Ship it!

**Review by sergiogcx — APPROVED** [review]
🚢

**Comment by johnclary** [comment]
Nice! I agree with @sergiogcx but let's hold off for @amenity to return and we'll scope a fancier footer. 

🚢 🛵💨

**Pull request merged**
