### PR TITLE
Add new funds to moped_funds

### PR DESCRIPTION
**Pull request by chiaberry**
## Associated issues

https://github.com/cityofaustin/atd-data-tech/issues/9676

We previously had the `fund_id` as an int, but one of the funds to be added is 820B, so I changed the column to text. 

## Testing
**URL to test:** 
~~Database changes, so you need to run locally or moped test~~

https://9676-add-fund-sources--atd-moped-main.netlify.app/moped/projects

**Steps to test:**

On the funding tab, add a new funding source and check for the new funds in the dropdown list. 

Screen Shot 2022-07-26 at 5 26 18 PM

---
#### Ship list
- [x] Code reviewed 
- [ ] Product manager approved
- [ ] ~Added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#) if applicable~

### CODE REVIEW

**Review by johnclary — APPROVED** [review]
🚢 🚢 🚢

**Review by frankhereford — APPROVED** [review]
Looks great, thank you @chiaberry!

**Review by mddilley — APPROVED** [review]
Tested this locally, and it looks great! 🚀

**Comment by chiaberry** [comment]
Thanks to Frank and Mike magic, this PR with database changes can be tested here! https://9676-add-fund-sources--atd-moped-main.netlify.app/moped/projects cc: @patrickm02L

**Review by patrickm02L — COMMENTED** [review]
Adding funds the first time was a little buggy. I got an error message when I tried to edit the first fund I selected from the drop down. 

I added 2 more funds that I was able to edit, then tested editing the first fund again and it worked like expected - the bug worked itself out. 

Before approving I would like to know it that bug was an anomaly or it's something that will persist for other users. 

https://user-images.githubusercontent.com/5566727/183954909-61d2a70f-b30b-4103-9b66-2d9ef3767d7b.mp4

**Comment by frankhereford** [comment]
@patrickm02L @chiaberry 
> Adding funds the first time was a little buggy. 

I think this is likely an issue with the test deployment WRT to the ECS instance and ALB. I'm going to 👀 this right now and follow up. Thanks!

**Comment by frankhereford** [comment]
It's confirmed that this is due to failing health check by the ALB when linking to the ECS instances. I am working on configuring these correctly to inspect the `/healthz` path on the `graphql-engine` host, which is there for just this purpose. 

The errant behavior that @patrickm02L noted above is not the result of this PR's contents, and it should not hold up on approval or merging.

Thanks again for the detailed report!

**Comment by patrickm02L** [comment]
> It's confirmed that this is due to failing health check by the ALB when linking to the ECS instances. I am working on configuring these correctly to inspect the `/healthz` path on the `graphql-engine` host, which is there for just this purpose.
> 
> The errant behavior that @patrickm02L noted above is not the result of this PR's contents, **and it should not hold up on approval or merging.**
> 
> Thanks again for the detailed report!

Good. Thanks for the check.

**Review by patrickm02L — APPROVED** [review]
Good to go! 🤘

**Comment by mateoclarke** [comment]
👍

**Pull request merged**
